/* ═══════════════════════════════════════════════════════════════════
   NICE — Documentation Hub
   Route: #/bridge?tab=documentation  (also rendered as a Bridge tab)

   The view module — handles render, search, navigation, and dynamic
   model-table substitution. Content lives in app/js/lib/docs-content.js
   (also the SSOT for the marketing site's www/docs/*.html pages,
   generated by scripts/build-docs.mjs).
═══════════════════════════════════════════════════════════════════ */

const DocsView = (() => {
  const title = 'Docs';
  const _esc = Utils.esc;

  let _el = null;
  let _activeSection = 'getting-started';
  let _searchQuery = '';

  const SECTIONS = DocsContent.SECTIONS;
  const BODIES = DocsContent.BODIES;

  function _iconSvg(name) {
    return `<svg class="docs-nav-icon icon icon-sm" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><use href="#icon-${name}"/></svg>`;
  }

  /* ══════════════════════════════════════════════════════════════════
     RENDER
  ══════════════════════════════════════════════════════════════════ */
  function render(el) {
    _el = el;

    // Read section from URL (?s=agents)
    const params = new URLSearchParams(location.hash.split('?')[1] || '');
    const urlSection = params.get('s');
    if (urlSection && SECTIONS.find(s => s.id === urlSection)) {
      _activeSection = urlSection;
    }

    el.innerHTML = `
      <div class="docs-wrap">
        <nav class="docs-sidebar">
          <div class="docs-search-wrap">
            <input type="text" class="docs-search" id="docs-search" placeholder="Search docs…" />
          </div>
          <ul class="docs-nav" id="docs-nav">
            ${SECTIONS.map(s => `
              <li>
                <button class="docs-nav-btn${s.id === _activeSection ? ' active' : ''}" data-section="${s.id}">
                  ${_iconSvg(s.icon)}
                  <span>${s.label}</span>
                </button>
              </li>
            `).join('')}
          </ul>
        </nav>
        <main class="docs-content" id="docs-content">
          ${_renderSection(_activeSection)}
        </main>
      </div>
    `;

    _bindEvents();
  }

  function _bindEvents() {
    // Section nav
    document.getElementById('docs-nav')?.addEventListener('click', e => {
      const btn = e.target.closest('[data-section]');
      if (!btn) return;
      _activeSection = btn.dataset.section;
      history.replaceState(null, '', `#/bridge?tab=documentation&s=${_activeSection}`);
      document.querySelectorAll('.docs-nav-btn').forEach(b => b.classList.toggle('active', b.dataset.section === _activeSection));
      const content = document.getElementById('docs-content');
      if (content) {
        content.innerHTML = _renderSection(_activeSection);
        content.scrollTop = 0;
      }
    });

    // Search result clicks → navigate to section
    document.getElementById('docs-content')?.addEventListener('click', e => {
      const hit = e.target.closest('.docs-search-hit[data-section]');
      if (!hit) return;
      _activeSection = hit.dataset.section;
      _searchQuery = '';
      const searchInput = document.getElementById('docs-search');
      if (searchInput) searchInput.value = '';
      history.replaceState(null, '', `#/bridge?tab=documentation&s=${_activeSection}`);
      document.querySelectorAll('.docs-nav-btn').forEach(b => b.classList.toggle('active', b.dataset.section === _activeSection));
      const content = document.getElementById('docs-content');
      if (content) {
        content.innerHTML = _renderSection(_activeSection);
        content.scrollTop = 0;
      }
    });

    // Search
    document.getElementById('docs-search')?.addEventListener('input', e => {
      _searchQuery = e.target.value.toLowerCase().trim();
      if (_searchQuery.length >= 2) {
        const content = document.getElementById('docs-content');
        if (content) content.innerHTML = _renderSearchResults();
      } else if (_searchQuery.length === 0) {
        const content = document.getElementById('docs-content');
        if (content) content.innerHTML = _renderSection(_activeSection);
      }
    });
  }

  /* ══════════════════════════════════════════════════════════════════
     SEARCH
  ══════════════════════════════════════════════════════════════════ */
  function _renderSearchResults() {
    const matches = [];
    for (const s of SECTIONS) {
      const content = _getSectionText(s.id);
      if (content.toLowerCase().includes(_searchQuery)) {
        const idx = content.toLowerCase().indexOf(_searchQuery);
        const start = Math.max(0, idx - 60);
        const end = Math.min(content.length, idx + _searchQuery.length + 60);
        const snippet = (start > 0 ? '…' : '') + content.slice(start, end) + (end < content.length ? '…' : '');
        matches.push({ section: s, snippet });
      }
    }

    if (!matches.length) {
      return `
        <div class="docs-empty">
          <h2>No results</h2>
          <p>No documentation matched "${_esc(_searchQuery)}".</p>
        </div>
      `;
    }

    return `
      <div class="docs-search-results">
        <h2>Search Results</h2>
        <p class="docs-muted">${matches.length} section${matches.length !== 1 ? 's' : ''} matched</p>
        ${matches.map(m => `
          <button class="docs-search-hit" data-section="${m.section.id}">
            <span class="docs-search-hit-title">${_iconSvg(m.section.icon)} ${m.section.label}</span>
            <span class="docs-search-hit-snippet">${_esc(m.snippet)}</span>
          </button>
        `).join('')}
      </div>
    `;
  }

  /* ══════════════════════════════════════════════════════════════════
     SECTION CONTENT
  ══════════════════════════════════════════════════════════════════ */
  function _renderSection(id) {
    const body = BODIES[id];
    if (!body) return '<p>Section not found.</p>';

    // Models section: replace the static fallback table with live rows
    // pulled from VaultView.MODEL_CATALOG when it's available.
    if (id === 'models' && typeof VaultView !== 'undefined' && VaultView.MODEL_CATALOG) {
      return body.replace(
        /<tbody>[\s\S]*?<\/tbody>/,
        `<tbody>${_renderLiveModelRows()}</tbody>`
      );
    }

    return body;
  }

  function _renderLiveModelRows() {
    return VaultView.MODEL_CATALOG.map(m => `
      <tr>
        <td>${_esc(m.name)}</td>
        <td>${_esc(m.provider)}</td>
        <td><span class="docs-badge docs-badge-${m.tier === 'free' ? 'free' : 'pro'}">${m.tier === 'free' ? 'Free' : 'Premium'}</span></td>
        <td>${_esc(m.description || '')}</td>
      </tr>
    `).join('');
  }

  function _getSectionText(id) {
    const el = document.createElement('div');
    el.innerHTML = _renderSection(id);
    return el.textContent || '';
  }

  /* ══════════════════════════════════════════════════════════════════
     CLEANUP
  ══════════════════════════════════════════════════════════════════ */
  function destroy() {
    _el = null;
    _searchQuery = '';
  }

  return { render, destroy, title };
})();
