/* ═══════════════════════════════════════════════════════════════════
   NICE — Spaceship Builder View
   No-code spaceship configuration: name, class, crew slots.
═══════════════════════════════════════════════════════════════════ */

const SpaceshipBuilderView = (() => {
  const title = 'Spaceship Builder';
  const _esc = Utils.esc;

  const CATEGORIES = ['Research','Analytics','Content','Engineering','Ops','Sales','Support','Legal','Marketing','Automation','Custom'];

  /* Map BlueprintUtils.SLOT_LABELS onto `roles.slug` values (FK target
     for `ship_slots.role_type`, NOT NULL). The slot vocabulary is
     starship-themed (Bridge / Tactical / Intel / …) and doesn't 1:1
     match the roles table; this is the closest functional mapping. A
     follow-up PR can let users pick the role per slot in the builder
     UI and retire this default. */
  const SLOT_ROLE_MAP = {
    Bridge: 'captain',
    Command: 'operations',
    Tactical: 'operations',
    Intel: 'research',
    Analytics: 'analytics',
    Operations: 'operations',
    Comms: 'communications',
    Science: 'research',
    Engineering: 'engineering',
    Support: 'support',
    Logistics: 'operations',
    Creative: 'design',
  };

  function _randomSerial(prefix) {
    return prefix + '-' + Math.random().toString(36).slice(2, 10).toUpperCase();
  }
  function _kebab(s) {
    return String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40) || 'spaceship';
  }

  /* Build the spaceship_blueprints row from the canonical form shape.
     Used for both INSERT (new ship), UPDATE (edit of own blueprint),
     and FORK (edit-on-catalog). User-authored ships are
     scope='community' + visibility='private' until they publish via
     the marketplace flow.

     `existingBlueprint` is the content backstop: the form surface is
     narrow (name, category, description, flavor, tags + slot picker),
     but the catalog carries `config.ship_system_prompt`, themed
     `card.subtitle`/`workflows`/`specialties`, and recommended_class.
     Overlay form values on top of the blueprint so the fork preserves
     everything the form can't represent. */
  function _buildShipBlueprintRow(form, user, existingBlueprint) {
    const existingConfig = existingBlueprint?.config || {};
    const existingCard = existingBlueprint?.card || {};
    const isFork = !!(existingBlueprint && existingBlueprint.creator_id !== user.id);
    const inheritIdentity = !!existingBlueprint && !isFork;
    return {
      ...(inheritIdentity && existingBlueprint.slug ? { slug: existingBlueprint.slug } : { slug: _kebab(form.name) + '-' + Math.random().toString(36).slice(2, 8) }),
      name: form.name,
      description: form.description || '',
      flavor: form.flavor || '',
      category: form.category || existingBlueprint?.category || '',
      rarity: form.rarity,
      scope: 'community',
      creator_id: user.id,
      visibility: 'private',
      config: {
        // Carry catalog's full config first (ship_system_prompt,
        // workflow_patterns, ship_voice, auto_theme), then overlay
        // form fields.
        ...existingConfig,
        stats: form.stats,
        // Caps are auto-generated by the form ("X operations",
        // "N agent slots") with no UI to edit them. The catalog's
        // themed caps ("ship product end-to-end", …) are the real
        // content — prefer existing when present.
        caps: (Array.isArray(existingConfig.caps) && existingConfig.caps.length) ? existingConfig.caps : (form.caps || []),
      },
      card: {
        ...existingCard,
        caps: (Array.isArray(existingCard.caps) && existingCard.caps.length) ? existingCard.caps : (form.caps || []),
      },
      ...(inheritIdentity && existingBlueprint.serial_key ? { serial_key: existingBlueprint.serial_key } : { serial_key: _randomSerial('USER') }),
      tags: form.tags?.length ? form.tags : (existingBlueprint?.tags || []),
    };
  }

  /* Insert one ship_slots row per slot. slot_position is 1-indexed
     (DB CHECK). role_type defaults via SLOT_ROLE_MAP; the form has no
     per-slot role picker today so every slot uses the label-derived
     default. */
  async function _insertShipSlots(blueprintId, slotCount) {
    if (!blueprintId || !slotCount || typeof SB === 'undefined' || !SB.client) return;
    const labels = (typeof BlueprintUtils !== 'undefined' && BlueprintUtils.SLOT_LABELS) || [];
    const rows = [];
    for (let i = 0; i < slotCount; i++) {
      const label = labels[i] || ('Agent ' + (i + 1));
      rows.push({
        spaceship_id: blueprintId,
        slot_position: i + 1,
        role_type: SLOT_ROLE_MAP[label] || 'operations',
        label,
        min_class: 'class-1',
      });
    }
    await SB.client.from('ship_slots').insert(rows);
  }

  /* Top-up ship_slots non-destructively: only INSERT the slots needed
     to reach `targetSlotCount`, leaving existing rows alone. The form
     has no UI for editing slot labels/role_types, so a delete-then-
     reinsert (the old _replaceShipSlots behavior) would silently
     destroy themed slot identity — catastrophic for forked catalog
     ships whose themed labels (Founder, Engineering Lead, …) we
     deliberately copied via _copyShipSlots. Rank-up still works: when
     a user gains a class, this adds the new generic slots on top of
     the themed ones. */
  async function _topUpShipSlots(blueprintId, targetSlotCount) {
    if (!blueprintId || !targetSlotCount || typeof SB === 'undefined' || !SB.client) return;
    const { data: existing } = await SB.client
      .from('ship_slots')
      .select('slot_position')
      .eq('spaceship_id', blueprintId)
      .order('slot_position');
    const have = Array.isArray(existing) ? existing.length : 0;
    if (have >= targetSlotCount) return;
    const labels = (typeof BlueprintUtils !== 'undefined' && BlueprintUtils.SLOT_LABELS) || [];
    const rows = [];
    for (let i = have; i < targetSlotCount; i++) {
      const label = labels[i] || ('Agent ' + (i + 1));
      rows.push({
        spaceship_id: blueprintId,
        slot_position: i + 1,
        role_type: SLOT_ROLE_MAP[label] || 'operations',
        label,
        min_class: 'class-1',
      });
    }
    await SB.client.from('ship_slots').insert(rows);
  }

  /* Clone the catalog ship's themed slots (label, role_type,
     default_agent_id, min_class) onto the forked blueprint. Without
     this, fork falls back to `_insertShipSlots(forkedId, count)` which
     generates generic Bridge/Command/Tactical/Intel/Analytics/Operations
     labels — losing the catalog's themed identity (e.g. The Loft's
     Founder/Engineering Lead/Designer/PM/…). Returns true if any rows
     were copied, false otherwise so the caller can fall back. */
  async function _copyShipSlots(srcBlueprintId, destBlueprintId) {
    if (!srcBlueprintId || !destBlueprintId || typeof SB === 'undefined' || !SB.client) return false;
    const { data: srcRows, error: fetchErr } = await SB.client
      .from('ship_slots')
      .select('slot_position, role_type, label, min_class, default_agent_id')
      .eq('spaceship_id', srcBlueprintId)
      .order('slot_position');
    if (fetchErr || !Array.isArray(srcRows) || !srcRows.length) return false;
    const insertRows = srcRows.map(s => ({ ...s, spaceship_id: destBlueprintId }));
    const { error: insertErr } = await SB.client.from('ship_slots').insert(insertRows);
    return !insertErr;
  }

  /** Slots are determined by XP rank via Gamification.getSlotTemplate() */
  function _getSlotConfig() {
    if (typeof Gamification !== 'undefined' && Gamification.getSlotTemplate) {
      const tpl = Gamification.getSlotTemplate();
      return {
        name: tpl.name || 'Spaceship',
        slots: tpl.slots.map(s => ({ max: s.maxRarity || 'Common', label: s.label || 'Crew ' + s.id }))
      };
    }
    return { name: 'Spaceship', slots: [{ max: 'Common', label: 'Bridge' }, { max: 'Common', label: 'Ops' }] };
  }

  const SLOT_COLORS = BlueprintUtils.RARITY_COLORS;

  function render(el) {
    // Guest mode: allow building ships without sign-in (saves to localStorage)

    const editId = new URLSearchParams(window.location.hash.split('?')[1] || '').get('edit');
    if (editId) {
      el.innerHTML = '<div class="loading-state"><p>Loading spaceship...</p></div>';
      _loadForEdit(el, editId);
    } else {
      _renderForm(el, null);
    }
  }

  async function _loadForEdit(el, id) {
    try {
      const raw = await SB.db('user_spaceships').get(id);
      // Hydrate from spaceship_blueprints when this activation links to
      // a blueprint. user_spaceships.config carries description/flavor/
      // tags but loses category, full caps, ship_system_prompt, themed
      // workflows, recommended_class, etc — the catalog richness lives
      // only on the blueprint row. Without this merge the edit form
      // would default category to "Research", caps to a generated
      // placeholder, and lose ship_system_prompt on save.
      let blueprint = null;
      if (raw?.blueprint_id) {
        try { blueprint = await SB.db('spaceship_blueprints').get(raw.blueprint_id); } catch (_) { blueprint = null; }
      }
      _renderForm(el, _hoistForForm(raw, blueprint));
    } catch (err) {
      el.innerHTML = `
        <div class="app-empty">
          <h2>Spaceship Not Found</h2>
          <p>${_esc(err.message)}</p>
          <div class="app-empty-acts"><a href="#/bridge?tab=spaceship" class="btn btn-sm">Back to Blueprints</a></div>
        </div>`;
    }
  }

  /**
   * Normalize a user_spaceships row for the form: hoist config JSONB (new shape)
   * or legacy `slots` bag to top-level so the form's read paths don't need to
   * care which shape the row was saved in. Also overlay catalog blueprint
   * content where the activation projection is incomplete (category, caps),
   * and carry `_sourceBlueprint` so `_submitShip` can pass it as backstop.
   */
  function _hoistForForm(raw, blueprint) {
    if (!raw) return raw;
    const cfg = (raw.config && Object.keys(raw.config).length ? raw.config : raw.slots) || {};
    // When a blueprint exists, treat it as the source of truth for
    // content. Activation rows often carry form defaults (category:
    // "Research") that aren't meaningful customizations, and the
    // builder writes both rows in sync for owned blueprints anyway.
    const merged = Object.assign({}, raw, {
      category:         blueprint?.category || raw.category || cfg.category || '',
      description:      blueprint?.description || raw.description || cfg.description || '',
      flavor:           blueprint?.flavor || raw.flavor || cfg.flavor || '',
      tags:             (Array.isArray(blueprint?.tags) && blueprint.tags.length ? blueprint.tags : (raw.tags && raw.tags.length ? raw.tags : (cfg.tags && cfg.tags.length ? cfg.tags : []))),
      slot_assignments: raw.slot_assignments || cfg.slot_assignments || {},
    });
    if (blueprint) merged._sourceBlueprint = blueprint;
    return merged;
  }

  function _renderForm(el, ship) {
    const isEdit = !!ship;
    const slotConfig = _getSlotConfig();
    // CATEGORIES is intentionally short, but the catalog uses a wider
    // vocabulary (e.g. "Startup", "Lab"). Without extending the
    // dropdown, the browser silently selects the first option and the
    // user sees the wrong category — then saves it.
    const selectedCategory = ship?.category || '';
    const allCategories = Array.from(new Set([...CATEGORIES, ...(selectedCategory ? [selectedCategory] : [])]));

    el.innerHTML = `
      <div class="builder-wrap">
        <div class="detail-back">
          <a href="#/bridge?tab=spaceship" class="btn btn-sm">
            <svg class="icon icon-sm" fill="none" stroke="currentColor" stroke-width="1.5"><use href="#icon-arrow-left"/></svg>
            Back to Blueprints
          </a>
        </div>

        <div class="builder-header">
          <svg class="builder-header-icon" fill="currentColor" stroke="none" style="width:28px;height:28px"><use href="#icon-spaceship"/></svg>
          <div>
            <h2 class="builder-title">${isEdit ? 'Edit Spaceship' : 'Create New Spaceship'}</h2>
            <p class="builder-sub">Configure your spaceship's identity and crew assignments. Slots are determined by your rank (${slotConfig.slots.length} available).</p>
          </div>
          <div class="builder-header-actions">
            <button type="button" class="btn btn-sm" id="btn-view-md" title="View as text">View as Text</button>
            <button type="button" class="btn btn-sm" id="btn-import-md" title="Import blueprint from text">Import</button>
          </div>
        </div>

        <form id="builder-form" class="builder-form">
          <!-- IDENTITY -->
          <fieldset class="builder-section">
            <legend class="builder-legend">Identity</legend>
            <div class="builder-row">
              <div class="auth-field">
                <label for="sb-name">Name</label>
                <input type="text" id="sb-name" required maxlength="40" placeholder="e.g. AURORA, VANGUARD, NEXUS" value="${_esc(ship?.name || '')}" />
              </div>
              <div class="auth-field">
                <label for="sb-category">Category</label>
                <select id="sb-category" class="filter-select builder-select">
                  ${allCategories.map(c => `<option value="${_esc(c)}" ${selectedCategory === c ? 'selected' : ''}>${_esc(c)}</option>`).join('')}
                </select>
              </div>
            </div>
          </fieldset>

          <!-- DETAILS -->
          <fieldset class="builder-section">
            <legend class="builder-legend">Details</legend>
            <div class="builder-row">
              <div class="auth-field" style="grid-column:1/-1">
                <label for="sb-desc">Description</label>
                <textarea id="sb-desc" rows="2" placeholder="What does this spaceship do?">${_esc(ship?.description || ship?.desc || '')}</textarea>
              </div>
              <div class="auth-field">
                <label for="sb-flavor">Tagline</label>
                <input type="text" id="sb-flavor" maxlength="60" placeholder="e.g. Ship faster. Scale smarter." value="${_esc(ship?.flavor || '')}" />
              </div>
              <div class="auth-field">
                <label for="sb-tags">Tags</label>
                <input type="text" id="sb-tags" placeholder="Comma-separated: saas, startup, tech" value="${_esc((ship?.tags || []).join(', '))}" />
              </div>
            </div>
          </fieldset>

          <!-- CREW SLOTS -->
          <fieldset class="builder-section">
            <legend class="builder-legend">Agent Slots</legend>
            <p class="builder-hint">Assign activated agents to slots. Each slot has a maximum rarity requirement.</p>
            <div class="builder-slot-grid" id="sb-slots"></div>
            <p class="builder-hint" id="sb-slot-count" style="margin-top:8px"></p>
          </fieldset>

          <!-- ACTIONS -->
          <div class="builder-actions">
            <div class="auth-error" id="builder-error"></div>
            <button type="submit" class="btn btn-primary" id="builder-submit">
              <svg class="icon icon-sm" fill="none" stroke="currentColor" stroke-width="1.5"><use href="#icon-check"/></svg>
              ${isEdit ? 'Save Changes' : 'Create Spaceship'}
            </button>
          </div>
        </form>

        <!-- Markdown Editor -->
        <div id="builder-md-editor" class="builder-md-editor" style="display:none">
          <div class="builder-md-toolbar">
            <button type="button" class="btn btn-sm" id="btn-md-back">Back to Form</button>
            <button type="button" class="btn btn-sm" id="btn-md-copy">Copy</button>
            <button type="button" class="btn btn-sm" id="btn-md-download">Download Blueprint</button>
          </div>
          <textarea id="builder-md-textarea" class="builder-md-textarea" spellcheck="false"></textarea>
          <div id="builder-md-status" class="builder-md-status"></div>
        </div>

        <!-- Import Modal -->
        <div id="builder-import-modal" class="builder-import-modal" style="display:none">
          <div class="builder-import-content">
            <h3>Import Spaceship Blueprint</h3>
            <textarea id="import-md-textarea" class="builder-md-textarea" spellcheck="false" placeholder="Paste blueprint text here..."></textarea>
            <div id="import-md-status" class="builder-md-status"></div>
            <div class="builder-actions-row">
              <button type="button" class="btn btn-primary" id="btn-import-confirm">Import</button>
              <button type="button" class="btn btn-sm" id="btn-import-cancel">Cancel</button>
            </div>
          </div>
        </div>
      </div>
    `;

    _renderSlots(ship?.slot_assignments || {});
    _bindForm(ship);
  }

  function _renderSlots(assignments) {
    const cls = _getSlotConfig();
    const grid = document.getElementById('sb-slots');
    const countEl = document.getElementById('sb-slot-count');
    if (!grid) return;

    // Get activated agents for dropdown
    const agents = (typeof Blueprints !== 'undefined' && Blueprints.getActivatedAgents)
      ? Blueprints.getActivatedAgents() : [];

    const rarityOrder = { Common: 0, Rare: 1, Epic: 2, Legendary: 3 };

    let assigned = 0;
    grid.innerHTML = cls.slots.map((slot, i) => {
      const agentId = assignments[i] || '';
      if (agentId) assigned++;
      const color = SLOT_COLORS[slot.max] || '#94a3b8';

      // Filter agents by rarity constraint
      const eligible = agents.filter(a => {
        const r = a.rarity || 'Common';
        return (rarityOrder[r] || 0) <= (rarityOrder[slot.max] || 0);
      });

      return `
        <div class="builder-slot-card ${agentId ? 'builder-slot-assigned' : ''}">
          <div class="builder-slot-header">
            <span class="builder-slot-label">${slot.label}</span>
            <span class="builder-slot-rarity" style="color:${color};border-color:${color}">${slot.max}</span>
          </div>
          <select class="filter-select builder-select builder-slot-select" data-slot="${i}">
            <option value="">— Empty —</option>
            ${eligible.map(a => `<option value="${a.id}" ${agentId === a.id ? 'selected' : ''}>${_esc(a.name)} (${a.rarity || 'Common'})</option>`).join('')}
          </select>
        </div>`;
    }).join('');

    if (countEl) countEl.textContent = `${assigned}/${cls.slots.length} slots assigned`;
  }

  function _bindForm(ship) {
    const form = document.getElementById('builder-form');

    _bindSlotEvents();

    // Submit
    if (form) {
      form.addEventListener('submit', (e) => {
        e.preventDefault();
        _submitShip(ship);
      });
    }

    // ── Markdown toggle ──
    document.getElementById('btn-view-md')?.addEventListener('click', () => {
      const bp = _formToBlueprint(ship);
      const md = BlueprintMarkdown.serialize(bp);
      document.getElementById('builder-md-textarea').value = md;
      document.getElementById('builder-form').style.display = 'none';
      document.getElementById('builder-md-editor').style.display = '';
      _updateMdStatus('builder-md-status', md);
    });

    document.getElementById('btn-md-back')?.addEventListener('click', () => {
      const md = document.getElementById('builder-md-textarea').value;
      const v = BlueprintMarkdown.validate(md);
      if (v.valid) {
        const bp = BlueprintMarkdown.parse(md);
        _populateForm(bp);
      }
      document.getElementById('builder-md-editor').style.display = 'none';
      document.getElementById('builder-form').style.display = '';
    });

    document.getElementById('btn-md-copy')?.addEventListener('click', () => {
      navigator.clipboard.writeText(document.getElementById('builder-md-textarea').value).then(() => {
        if (typeof Notify !== 'undefined') Notify.send({ title: 'Copied to clipboard', type: 'success' });
      });
    });

    document.getElementById('btn-md-download')?.addEventListener('click', () => {
      const ta = document.getElementById('builder-md-textarea');
      const name = (document.getElementById('sb-name')?.value || 'spaceship').toLowerCase().replace(/\s+/g, '-');
      const blob = new Blob([ta.value], { type: 'text/markdown' });
      const a = document.createElement('a');
      a.href = URL.createObjectURL(blob);
      a.download = name + '.md';
      a.click();
      URL.revokeObjectURL(a.href);
    });

    document.getElementById('builder-md-textarea')?.addEventListener('input', _debounce(() => {
      _updateMdStatus('builder-md-status', document.getElementById('builder-md-textarea').value);
    }, 300));

    // ── Import modal ──
    document.getElementById('btn-import-md')?.addEventListener('click', () => {
      document.getElementById('import-md-textarea').value = '';
      document.getElementById('import-md-status').textContent = '';
      document.getElementById('builder-import-modal').style.display = '';
    });

    document.getElementById('btn-import-cancel')?.addEventListener('click', () => {
      document.getElementById('builder-import-modal').style.display = 'none';
    });

    document.getElementById('import-md-textarea')?.addEventListener('input', _debounce(() => {
      _updateMdStatus('import-md-status', document.getElementById('import-md-textarea').value);
    }, 300));

    document.getElementById('btn-import-confirm')?.addEventListener('click', () => {
      const md = document.getElementById('import-md-textarea').value;
      const v = BlueprintMarkdown.validate(md);
      if (!v.valid) {
        document.getElementById('import-md-status').textContent = v.errors.join('; ');
        return;
      }
      const bp = BlueprintMarkdown.parse(md);
      _populateForm(bp);
      document.getElementById('builder-import-modal').style.display = 'none';
      if (typeof Notify !== 'undefined') Notify.send({ title: 'Blueprint imported', type: 'success' });
    });
  }

  function _bindSlotEvents() {
    document.querySelectorAll('.builder-slot-select').forEach(sel => {
      sel.addEventListener('change', () => {
        sel.closest('.builder-slot-card')?.classList.toggle('builder-slot-assigned', !!sel.value);
        const cls = _getSlotConfig();
        const assigned = document.querySelectorAll('.builder-slot-select').length
          ? [...document.querySelectorAll('.builder-slot-select')].filter(s => s.value).length : 0;
        const countEl = document.getElementById('sb-slot-count');
        if (countEl) countEl.textContent = `${assigned}/${cls.slots.length} slots assigned`;
      });
    });
  }

  function _getSlotAssignments() {
    const assignments = {};
    document.querySelectorAll('.builder-slot-select').forEach(sel => {
      if (sel.value) assignments[sel.dataset.slot] = sel.value;
    });
    return assignments;
  }

  async function _submitShip(existingShip) {
    const errEl = document.getElementById('builder-error');
    const btn   = document.getElementById('builder-submit');
    errEl.textContent = '';
    btn.disabled = true;
    btn.textContent = existingShip ? 'Saving...' : 'Creating...';

    const user = State.get('user');
    const name     = document.getElementById('sb-name').value.trim();
    const category = document.getElementById('sb-category').value;
    const desc     = document.getElementById('sb-desc').value.trim();
    const flavor   = document.getElementById('sb-flavor').value.trim();
    const tags     = document.getElementById('sb-tags').value.split(',').map(t => t.trim()).filter(Boolean);
    const slots    = _getSlotAssignments();

    if (!name) {
      errEl.textContent = 'Ship name is required.';
      btn.disabled = false;
      btn.textContent = existingShip ? 'Save Changes' : 'Create Spaceship';
      return;
    }

    const cls = _getSlotConfig();
    // Ship rarity mirrors the class capacity (Scout=Common, Frigate=Rare, …).
    // Assigned crew can only be ≤ this rarity, so the class cap is the ceiling.
    const rarity = cls.slots[0]?.max || 'Common';
    const stats = { crew: String(Object.keys(slots).length), slots: String(cls.slots.length) };
    const caps  = [category + ' operations', cls.slots.length + ' agent slots'];
    const configBody = { description: desc, flavor, tags, stats, caps };
    const row = {
      name,
      status: existingShip?.status || 'standby',
      category,
      rarity,
      config: configBody,
    };

    // Canonical form snapshot — passed to _buildShipBlueprintRow.
    const form = {
      name, description: desc, flavor, category, rarity, tags, stats, caps,
    };

    try {
      let shipId;
      if (user && typeof SB !== 'undefined' && SB.isReady()) {
        // Authenticated path — writes both spaceship_blueprints (the
        // template, with ship_slots child rows) AND user_spaceships
        // (the activation, with user_ship_slots child rows via
        // ShipSlots.setForShip). User-authored ships are
        // scope='community' + visibility='private' until publish.
        //
        // Edit path: if the existing user_spaceships row points at a
        // catalog blueprint (creator_id != user.id), we *fork* — insert
        // a new private blueprint and repoint user_spaceships.blueprint_id.
        // Mutating the catalog row would silently no-op under RLS and
        // also corrupt a shared template. Only blueprints the user
        // already owns can be updated in place.
        if (existingShip) {
          // Prefer the blueprint hydrated by _loadForEdit; fall back
          // to a fresh fetch when the user reached this surface via an
          // unusual path that bypassed _hoistForForm.
          let blueprintId = existingShip.blueprint_id || null;
          let existingBlueprint = existingShip._sourceBlueprint || null;
          if (!existingBlueprint && blueprintId) {
            try { existingBlueprint = await SB.db('spaceship_blueprints').get(blueprintId); } catch (_) { existingBlueprint = null; blueprintId = null; }
          }
          const ownedByMe = !!(existingBlueprint && existingBlueprint.creator_id === user.id);
          // Always pass existingBlueprint — _buildShipBlueprintRow uses
          // it as the content backstop and detects fork-vs-update
          // internally via creator_id.
          const blueprintRow = _buildShipBlueprintRow(form, user, existingBlueprint);
          if (ownedByMe && blueprintId) {
            await SB.db('spaceship_blueprints').update(blueprintId, blueprintRow);
            await _topUpShipSlots(blueprintId, cls.slots.length);
          } else {
            const inserted = await SB.db('spaceship_blueprints').create(blueprintRow);
            const forkedId = inserted?.id || null;
            if (forkedId) {
              // Try to clone the catalog's themed ship_slots first;
              // fall back to generated generic slots if the catalog
              // has none (shouldn't happen, defensive).
              const copied = blueprintId ? await _copyShipSlots(blueprintId, forkedId) : false;
              if (!copied) await _insertShipSlots(forkedId, cls.slots.length);
              row.blueprint_id = forkedId;
            }
          }
          await SB.db('user_spaceships').update(existingShip.id, row);
          shipId = existingShip.id;
        } else {
          // Create path — insert the blueprint first so we have an id
          // to link from user_spaceships.blueprint_id, then ship_slots,
          // then the user_spaceships activation.
          const blueprintRow = _buildShipBlueprintRow(form, user, null);
          const inserted = await SB.db('spaceship_blueprints').create(blueprintRow);
          const blueprintId = inserted?.id || null;
          if (blueprintId) {
            await _insertShipSlots(blueprintId, cls.slots.length);
            row.blueprint_id = blueprintId;
          }
          row.user_id = user.id;
          const { ship: created } = await Blueprints.findOrCreateActiveShip(blueprintId, () => row);
          shipId = created?.id;
        }
        if (shipId && typeof ShipSlots !== 'undefined') {
          await ShipSlots.setForShip(shipId, slots);
        }
      } else {
        // Guest mode: save to localStorage
        shipId = existingShip?.id || ('guest-ship-' + Date.now());
      }

      if (shipId && !existingShip) {
        if (typeof Gamification !== 'undefined') {
          Gamification.addXP('launch_spaceship');
          Gamification.checkAchievements();
        }
        const shipObj = {
          id: shipId, name, category, description: desc, flavor, tags, type: 'spaceship',
          rarity, status: 'standby', _guest: !user,
          config: { slot_assignments: slots },
          stats: { crew: String(Object.keys(slots).length), slots: String(cls.slots.length) },
          metadata: { caps: [category + ' operations', cls.slots.length + ' agent slots'] },
        };
        const ships = State.get('spaceships') || [];
        ships.push(shipObj);
        State.set('spaceships', ships);
        // Persist guest ships to localStorage
        if (!user) {
          const custom = JSON.parse(localStorage.getItem(Utils.KEYS.customShips) || '[]');
          custom.push(shipObj);
          localStorage.setItem(Utils.KEYS.customShips, JSON.stringify(custom));
        }
        if (typeof Blueprints !== 'undefined') Blueprints.activateShip(shipId);
        _showSetupChoice(shipId, { name, category, description: desc, flavor, tags, slotCount: cls.slots.length, slots: row.slots });
        return;
      }
      if (shipId) {
        localStorage.setItem(Utils.KEYS.mcShip, shipId);
        window.dispatchEvent(new StorageEvent('storage', { key: Utils.KEYS.mcShip, newValue: shipId }));
      }
      Router.navigate('#/bridge?tab=schematic');
    } catch (err) {
      errEl.textContent = err.message || 'Failed to save spaceship.';
      btn.disabled = false;
      btn.textContent = existingShip ? 'Save Changes' : 'Create Spaceship';
    }
  }

  /** Show crew setup choice modal after spaceship creation */
  function _showSetupChoice(shipId, shipData) {
    // Remove any existing modal
    document.getElementById('crew-setup-modal')?.remove();

    const modal = document.createElement('div');
    modal.id = 'crew-setup-modal';
    modal.className = 'builder-import-modal';
    modal.innerHTML = `
      <div class="crew-setup-content">
        <h2 class="crew-setup-title">${Utils.esc(shipData.name)} Created</h2>
        <p class="crew-setup-sub">How would you like to set up your crew?</p>

        <div class="crew-setup-options">
          <button class="crew-setup-option crew-setup-recommended" id="btn-ai-setup">
            <span class="crew-setup-icon">&#9733;</span>
            <span class="crew-setup-label">AI Auto Setup</span>
            <span class="crew-setup-desc">Let NICE design ${shipData.slotCount} agents tailored to your business</span>
          </button>
          <button class="crew-setup-option" id="btn-manual-setup">
            <span class="crew-setup-icon">&#9881;</span>
            <span class="crew-setup-label">Manual Setup</span>
            <span class="crew-setup-desc">Choose agents yourself from the blueprint catalog</span>
          </button>
          <button class="crew-setup-option" id="btn-skip-setup">
            <span class="crew-setup-icon">&#8594;</span>
            <span class="crew-setup-label">Skip for Now</span>
            <span class="crew-setup-desc">Set up crew later from the Schematic view</span>
          </button>
        </div>

        <div id="crew-setup-status" class="crew-setup-status" style="display:none">
          <div class="crew-setup-spinner"></div>
          <p id="crew-setup-msg">Generating your crew...</p>
        </div>
      </div>`;
    document.body.appendChild(modal);

    // AI Auto Setup
    document.getElementById('btn-ai-setup').addEventListener('click', async () => {
      const optionsEl = modal.querySelector('.crew-setup-options');
      const statusEl = document.getElementById('crew-setup-status');
      const msgEl = document.getElementById('crew-setup-msg');
      optionsEl.style.display = 'none';
      statusEl.style.display = '';
      msgEl.textContent = 'Analyzing your business...';

      try {
        // Generate agents via AI
        const result = await CrewGenerator.generate(shipData);
        if (result.error || !result.agents.length) {
          msgEl.textContent = result.error || 'Failed to generate agents. Try manual setup.';
          setTimeout(() => { optionsEl.style.display = ''; statusEl.style.display = 'none'; }, 2000);
          return;
        }

        msgEl.textContent = 'Creating ' + result.agents.length + ' agents...';

        // Save and assign
        const saved = await CrewGenerator.saveAndAssign(shipId, result.agents, { slots: shipData.slots || {} });
        if (!saved.savedAgents.length) {
          msgEl.textContent = 'Failed to save agents. Try manual setup.';
          setTimeout(() => { optionsEl.style.display = ''; statusEl.style.display = 'none'; }, 2000);
          return;
        }

        msgEl.textContent = saved.savedAgents.length + ' agents deployed!';
        if (typeof Notify !== 'undefined') {
          Notify.send({ title: saved.savedAgents.length + ' agents created for ' + shipData.name, type: 'success' });
        }

        setTimeout(() => {
          modal.remove();
          Router.navigate('#/bridge');
        }, 1200);
      } catch (e) {
        msgEl.textContent = 'Error: ' + (e.message || 'Unknown error');
        setTimeout(() => { optionsEl.style.display = ''; statusEl.style.display = 'none'; }, 2000);
      }
    });

    // Manual Setup → go to Bridge Blueprints/Agents tab
    document.getElementById('btn-manual-setup').addEventListener('click', () => {
      modal.remove();
      Router.navigate('#/bridge?tab=agent');
    });

    // Skip → go to Schematic
    document.getElementById('btn-skip-setup').addEventListener('click', () => {
      modal.remove();
      Router.navigate('#/bridge');
    });
  }

  function _debounce(fn, ms) { let t; return function() { clearTimeout(t); t = setTimeout(fn, ms); }; }

  /** Build a blueprint object from the current form state */
  function _formToBlueprint(ship) {
    const name     = document.getElementById('sb-name')?.value?.trim() || '';
    const category = document.getElementById('sb-category')?.value || '';
    const desc     = document.getElementById('sb-desc')?.value?.trim() || '';
    const flavor   = document.getElementById('sb-flavor')?.value?.trim() || '';
    const tags     = (document.getElementById('sb-tags')?.value || '').split(',').map(t => t.trim()).filter(Boolean);
    const slots    = _getSlotAssignments();
    const cls      = _getSlotConfig();

    return {
      type: 'spaceship',
      name: name,
      category: category,
      description: desc,
      flavor: flavor,
      tags: tags,
      rarity: ship?.rarity || '',
      serial_key: ship?.serial_key || '',
      config: { slot_assignments: slots },
      stats: { crew: String(Object.keys(slots).length), slots: String(cls.slots.length) },
      metadata: {
        recommended_class: ship?.metadata?.recommended_class || '',
        caps: ship?.metadata?.caps || [category + ' operations'],
        crew: Object.keys(slots).map(s => ({
          slot: parseInt(s, 10),
          role: cls.slots[parseInt(s, 10)]?.label || 'Crew ' + s,
          agent: slots[s],
        })),
      },
    };
  }

  /** Populate the form from a parsed blueprint */
  function _populateForm(bp) {
    const el = (id) => document.getElementById(id);
    if (el('sb-name')) el('sb-name').value = bp.name || '';
    if (el('sb-category')) el('sb-category').value = bp.category || 'Research';
    if (el('sb-desc')) el('sb-desc').value = bp.description || '';
    if (el('sb-flavor')) el('sb-flavor').value = bp.flavor || '';
    if (el('sb-tags')) el('sb-tags').value = (bp.tags || []).join(', ');

    // Re-render slots with imported assignments
    const assignments = (bp.config && bp.config.slot_assignments) || {};
    _renderSlots(assignments);
    _bindSlotEvents();
  }

  /** Show validation status for markdown textarea */
  function _updateMdStatus(elId, md) {
    const statusEl = document.getElementById(elId);
    if (!statusEl || !md) return;
    const v = BlueprintMarkdown.validate(md);
    if (!v.valid) {
      statusEl.textContent = v.errors.join('; ');
      statusEl.className = 'builder-md-status error';
    } else if (v.warnings.length) {
      statusEl.textContent = v.warnings.join('; ');
      statusEl.className = 'builder-md-status warn';
    } else {
      statusEl.textContent = 'Valid blueprint';
      statusEl.className = 'builder-md-status ok';
    }
  }

  return { title, render };
})();
