#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════════
   NICE — Marketing Pricing Generator

   Generates www/pricing.html from the canonical app SSOTs:
     • app/js/lib/token-config.js   (pools, model→pool→weight map)
     • app/js/lib/stripe-config.js  (subscriptions, top-ups, payment links)
     • app/js/lib/model-catalog.js  (display names, providers)

   Run after editing any of those:
     npm run build:pricing

   Generated file includes a "DO NOT EDIT" header. Edit the source SSOTs
   instead and re-run this script.
═══════════════════════════════════════════════════════════════════ */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { createRequire } from 'node:module';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');
const outPath = join(repoRoot, 'www', 'pricing.html');
const require = createRequire(import.meta.url);

const TokenConfig = require(join(repoRoot, 'app/js/lib/token-config.js'));
const StripeConfig = require(join(repoRoot, 'app/js/lib/stripe-config.js'));
const { MODEL_CATALOG } = require(join(repoRoot, 'app/js/lib/model-catalog.js'));

/* ── Helpers ──────────────────────────────────────────────────── */

const byId = id => MODEL_CATALOG.find(m => m.id === id) || null;

function modelsInPool(poolId) {
  return TokenConfig.modelsInPool(poolId).map(byId).filter(Boolean);
}

function freeModels() {
  return MODEL_CATALOG.filter(m => TokenConfig.isFreeModel(m.id));
}

function fmtPrice(n) {
  return Number.isInteger(n) ? `$${n}` : `$${n.toFixed(2)}`;
}

function fmtTokens(n) {
  return n.toLocaleString('en-US');
}

function escapeAttr(s) {
  return String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
}

function modelLi(model) {
  return `              <li>${model.name}</li>`;
}

/** Boost / Max top-up pair → "$29.99 / $49.99" + "+1,000 or +2,500 tokens" */
function topUpRange(poolId) {
  const tops = StripeConfig.topUpsForPool(poolId).slice().sort((a, b) => a.price - b.price);
  if (tops.length !== 2) {
    throw new Error(`Expected exactly 2 top-ups for pool ${poolId}, got ${tops.length}`);
  }
  const [boost, max] = tops;
  return {
    boost, max,
    priceLine: `${fmtPrice(boost.price)}<span style="font-size:0.5em;color:var(--text-muted)"> / ${fmtPrice(max.price)}</span>`,
    tokenLine: `+${fmtTokens(boost.tokens)} or +${fmtTokens(max.tokens)} tokens`,
  };
}

/* ── Page render ──────────────────────────────────────────────── */

const GENERATED_HEADER = `<!--
  AUTO-GENERATED by scripts/build-pricing.mjs from the live SSOTs:
    • app/js/lib/token-config.js  (pools + model→pool→weight)
    • app/js/lib/stripe-config.js (subscriptions + top-ups + payment links)
    • app/js/lib/model-catalog.js (display names, providers)
  DO NOT EDIT THIS FILE. Edit the sources above and re-run:
    npm run build:pricing
-->`;

function render() {
  const proSub = StripeConfig.SUBSCRIPTIONS.pro;
  const claudeSub = StripeConfig.SUBSCRIPTIONS.claude;
  const premiumSub = StripeConfig.SUBSCRIPTIONS.premium;

  const standardAllowance = TokenConfig.POOLS.standard.monthlyAllowance;
  const claudeAllowance = TokenConfig.POOLS.claude.monthlyAllowance;
  const premiumAllowance = TokenConfig.POOLS.premium.monthlyAllowance;

  const standardModels = modelsInPool('standard');
  const claudeModels = modelsInPool('claude');
  const premiumModels = modelsInPool('premium');
  const freeModelNames = freeModels().map(m => m.name).join(', ');

  const sonnetWeight = TokenConfig.weightFor('claude-4-6-sonnet');
  const opusWeight = TokenConfig.weightFor('claude-4-7-opus');

  const standardRange = topUpRange('standard');
  const claudeRange = topUpRange('claude');
  const premiumRange = topUpRange('premium');

  const standardModelsList = standardModels.map(m => m.name).join(', ');
  const premiumModelsList = premiumModels.map(m => m.name).join(', ');

  const metaDescription = `NICE pricing: free tier with unlimited ${freeModelNames}. Pro at ${fmtPrice(proSub.price)}/month. Claude and Premium add-ons ${fmtPrice(claudeSub.price)} each. Token top-ups from ${fmtPrice(standardRange.boost.price)}.`;

  return `<!DOCTYPE html>
<html lang="en" data-mode="dark">
${GENERATED_HEADER}
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Pricing — NICE SPACESHIP</title>
  <meta name="description" content="${escapeAttr(metaDescription)}" />
  <link rel="icon" href="/assets/logo.svg" type="image/svg+xml" />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Fira+Code:wght@400&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="/css/site.css" />
</head>
<body>
  <header id="site-header"></header>
  <main>
    <section class="hero" style="padding-bottom:20px">
      <div class="container">
        <h1>Simple, Transparent Pricing</h1>
        <p class="hero-sub">Free to start. Pay only when you need premium AI models.</p>
      </div>
    </section>

    <section class="section">
      <div class="container">
        <h2 style="text-align:center;margin-bottom:8px">Plans</h2>
        <p style="text-align:center;color:var(--text-muted);margin-bottom:0">${freeModelNames} is free for everyone. Pro unlocks everything else.</p>
        <div class="pricing-grid">
          <div class="pricing-card">
            <h3>Free</h3>
            <div class="pricing-price">$0</div>
            <div class="pricing-period">forever</div>
            <ul class="pricing-features">
              <li>6 agent slots</li>
              <li>Common blueprints</li>
              <li>${freeModelNames} (unlimited)</li>
              <li>XP progression to Legendary</li>
              <li>All core integrations</li>
            </ul>
            <a href="https://nicespaceship.ai" class="btn-secondary" style="width:100%;text-align:center">Get Started Free</a>
          </div>
          <div class="pricing-card featured">
            <h3>Pro</h3>
            <div class="pricing-price">${fmtPrice(proSub.price)}</div>
            <div class="pricing-period">per month</div>
            <ul class="pricing-features">
              <li>12 agent slots</li>
              <li>Legendary blueprints instantly</li>
              <li>${fmtTokens(standardAllowance)} Standard tokens / month</li>
              <li>Standard pool models (${standardModelsList})</li>
              <li>Token top-ups that never expire</li>
            </ul>
            <a href="${proSub.paymentLinkUrl}" class="btn-primary" style="width:100%;text-align:center">Choose Pro</a>
          </div>
        </div>
      </div>
    </section>

    <section class="section section-alt">
      <div class="container">
        <h2 style="text-align:center;margin-bottom:8px">Frontier Add-ons</h2>
        <p style="text-align:center;color:var(--text-muted);margin-bottom:32px">Pro subscribers can stack optional add-ons for the frontier models. Each add-on is its own subscription with its own monthly token pool.</p>
        <div class="pricing-grid">
          <div class="pricing-card">
            <h3>Claude Add-on</h3>
            <div class="pricing-price">+${fmtPrice(claudeSub.price)}</div>
            <div class="pricing-period">per month, on top of Pro</div>
            <ul class="pricing-features">
${claudeModels.map(modelLi).join('\n')}
              <li>${fmtTokens(claudeAllowance)} Claude tokens / month</li>
              <li>Sonnet = ${sonnetWeight} tokens / message</li>
              <li>Opus = ${opusWeight} tokens / message</li>
            </ul>
            <a href="${claudeSub.paymentLinkUrl}" class="btn-secondary" style="width:100%;text-align:center">Add Claude</a>
          </div>
          <div class="pricing-card">
            <h3>Premium Add-on</h3>
            <div class="pricing-price">+${fmtPrice(premiumSub.price)}</div>
            <div class="pricing-period">per month, on top of Pro</div>
            <ul class="pricing-features">
${premiumModels.map(modelLi).join('\n')}
              <li>${fmtTokens(premiumAllowance)} Premium tokens / month (weighted)</li>
            </ul>
            <a href="${premiumSub.paymentLinkUrl}" class="btn-secondary" style="width:100%;text-align:center">Add Premium</a>
          </div>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="container">
        <h2 style="text-align:center;margin-bottom:8px">Token Top-ups</h2>
        <p style="text-align:center;color:var(--text-muted);margin-bottom:32px">Pro only. One-time purchases that credit the matching pool and never expire. Max packs are the best value (17% off).</p>
        <div class="pricing-grid">
          <div class="pricing-card">
            <h3>Standard</h3>
            <div class="pricing-price">${standardRange.priceLine}</div>
            <div class="pricing-period">${standardRange.tokenLine}</div>
            <ul class="pricing-features">
              <li>Spends on Standard pool models</li>
              <li>Kicks in after monthly allowance</li>
              <li>Never expires</li>
            </ul>
            <a href="https://nicespaceship.ai/#/security?tab=wallet" class="btn-secondary" style="width:100%;text-align:center">Buy Standard</a>
          </div>
          <div class="pricing-card featured">
            <h3>Claude</h3>
            <div class="pricing-price">${claudeRange.priceLine}</div>
            <div class="pricing-period">${claudeRange.tokenLine}</div>
            <ul class="pricing-features">
              <li>Requires Claude Add-on</li>
              <li>Spends on ${claudeModels.map(m => m.name).join(' and ')}</li>
              <li>Never expires</li>
            </ul>
            <a href="https://nicespaceship.ai/#/security?tab=wallet" class="btn-primary" style="width:100%;text-align:center">Buy Claude</a>
          </div>
          <div class="pricing-card">
            <h3>Premium</h3>
            <div class="pricing-price">${premiumRange.priceLine}</div>
            <div class="pricing-period">${premiumRange.tokenLine}</div>
            <ul class="pricing-features">
              <li>Requires Premium Add-on</li>
              <li>${premiumModelsList}</li>
              <li>Never expires</li>
            </ul>
            <a href="https://nicespaceship.ai/#/security?tab=wallet" class="btn-secondary" style="width:100%;text-align:center">Buy Premium</a>
          </div>
        </div>
      </div>
    </section>

    <section class="section section-alt" style="text-align:center">
      <div class="container">
        <h2>Replace your entire stack</h2>
        <p style="color:var(--text-muted);margin-bottom:24px">The average SMB spends over $1,300 / month on marketing tools and agencies.</p>
        <p style="font-size:1.2rem;color:var(--color-success);font-weight:700">NICE Pro replaces most of them for ${fmtPrice(proSub.price)} / month.</p>
        <p style="color:var(--text-muted)">Stack frontier add-ons only when you need them.</p>
        <a href="/" class="btn-secondary" style="margin-top:24px">See the full breakdown</a>
      </div>
    </section>
  </main>
  <footer id="site-footer" class="footer"></footer>
  <script src="/js/theme-lite.js"></script>
  <script src="/js/nav.js"></script>
  <script>ThemeLite.init(); Nav.render(); Nav.renderFooter();</script>
</body>
</html>
`;
}

/* ── Run ──────────────────────────────────────────────────────── */

writeFileSync(outPath, render());
console.log(`  wrote www/pricing.html`);
console.log(`\n✓ Generated from app/js/lib/{token-config,stripe-config,model-catalog}.js`);
