#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════════
   NICE — Marketing Docs Generator

   Reads app/js/lib/docs-content.js (the SSOT for documentation
   content) and generates one HTML page per section in www/docs/,
   plus an index.html landing page.

   Run after editing docs-content.js:
     npm run build:docs

   Generated files include a "DO NOT EDIT" header. Edit the source
   instead and re-run this script.
═══════════════════════════════════════════════════════════════════ */

import { readFileSync, writeFileSync, readdirSync, unlinkSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { createRequire } from 'node:module';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');
const docsOutDir = join(repoRoot, 'www', 'docs');
const contentPath = join(repoRoot, 'app', 'js', 'lib', 'docs-content.js');

// docs-content.js is UMD — load it via CommonJS require so its
// `module.exports = factory()` branch fires and we get the export.
const require = createRequire(import.meta.url);
const { SECTIONS, BODIES } = require(contentPath);

const GENERATED_HEADER = `<!--
  AUTO-GENERATED by scripts/build-docs.mjs from
  app/js/lib/docs-content.js. DO NOT EDIT THIS FILE.
  Edit the source and re-run: npm run build:docs
-->`;

function commonHead(title, description) {
  return `<!DOCTYPE html>
<html lang="en" data-mode="dark">
${GENERATED_HEADER}
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
  <meta name="description" content="${escapeAttr(description)}" />
  <link rel="icon" href="/assets/logo.svg" type="image/svg+xml" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Fira+Code:wght@400&family=Orbitron:wght@900&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="/css/site.css" />
</head>`;
}

function commonFooter() {
  return `  <footer id="site-footer" class="footer"></footer>
  <script src="/js/theme-lite.js"></script>
  <script src="/js/nav.js"></script>
  <script>ThemeLite.init(); Nav.render(); Nav.renderFooter();</script>
</body>
</html>`;
}

function sidebar(activeSlug) {
  const links = SECTIONS.map(s => {
    const active = s.slug === activeSlug ? ' class="active"' : '';
    return `      <a href="/docs/${s.slug}"${active}>${s.label}</a>`;
  }).join('\n');
  return `    <nav class="docs-sidebar" id="docs-sidebar">
      <h4>Documentation</h4>
${links}
    </nav>`;
}

function escapeAttr(s) {
  return String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
}

function renderSectionPage(section) {
  const body = BODIES[section.id];
  if (!body) {
    throw new Error(`No body for section "${section.id}"`);
  }
  const title = `${section.label} — NICE Documentation`;
  return `${commonHead(title, section.description)}
<body>
  <header id="site-header"></header>
  <div class="docs-layout">
${sidebar(section.slug)}
    <main class="docs-content">${body}    </main>
  </div>
${commonFooter()}
`;
}

function renderIndexPage() {
  const cards = SECTIONS.map(s => `        <a href="/docs/${s.slug}" class="docs-card">
          <div class="docs-card-icon"><i class="fa-solid ${s.marketingIcon}"></i></div>
          <h3>${s.label}</h3>
          <p>${escapeAttr(s.description)}</p>
        </a>`).join('\n');

  return `${commonHead('Documentation — NICE SPACESHIP', 'NICE documentation: get started, concepts, AI models, integrations, and more.')}
<body>
  <header id="site-header"></header>
  <div class="docs-layout">
${sidebar(null)}
    <main class="docs-content">
      <h1>NICE Documentation</h1>
      <p class="docs-lead">Everything you need to build, deploy, and manage AI agent fleets.</p>

      <div class="docs-cards">
${cards}
      </div>
    </main>
  </div>
${commonFooter()}
`;
}

/* ── Run ──────────────────────────────────────────────────────── */

// Delete any orphan .html files in www/docs/ that don't correspond
// to a current section. Keeps the directory clean when sections are
// renamed or removed.
const validSlugs = new Set(['index', ...SECTIONS.map(s => s.slug)]);
for (const file of readdirSync(docsOutDir)) {
  if (!file.endsWith('.html')) continue;
  const slug = file.replace(/\.html$/, '');
  if (!validSlugs.has(slug)) {
    unlinkSync(join(docsOutDir, file));
    console.log(`  removed www/docs/${file} (no matching section)`);
  }
}

// Write the index page
writeFileSync(join(docsOutDir, 'index.html'), renderIndexPage());
console.log(`  wrote www/docs/index.html`);

// Write one page per section
for (const section of SECTIONS) {
  const filePath = join(docsOutDir, `${section.slug}.html`);
  writeFileSync(filePath, renderSectionPage(section));
  console.log(`  wrote www/docs/${section.slug}.html`);
}

console.log(`\n✓ Generated ${SECTIONS.length + 1} files from app/js/lib/docs-content.js`);
