#!/usr/bin/env node
/**
 * NICE — Generate TypeScript interfaces from SQL migration files.
 * Usage: node scripts/gen-types.js
 * Output: app/js/lib/db-types.d.ts
 *
 * Simple regex-based parser — not a full SQL parser.
 * Handles CREATE TABLE statements with common column types.
 */

const fs = require('fs');
const path = require('path');

const MIGRATIONS_DIR = path.resolve(__dirname, '..', 'migrations');
const OUTPUT_FILE = path.resolve(__dirname, '..', 'app', 'js', 'lib', 'db-types.d.ts');

// Map SQL types to TypeScript types
const TYPE_MAP = {
  'uuid': 'string',
  'text': 'string',
  'varchar': 'string',
  'char': 'string',
  'integer': 'number',
  'int': 'number',
  'bigint': 'number',
  'smallint': 'number',
  'serial': 'number',
  'float': 'number',
  'double': 'number',
  'numeric': 'number',
  'decimal': 'number',
  'real': 'number',
  'boolean': 'boolean',
  'bool': 'boolean',
  'jsonb': 'Record<string, unknown>',
  'json': 'Record<string, unknown>',
  'timestamptz': 'string',
  'timestamp': 'string',
  'date': 'string',
  'time': 'string',
};

function sqlTypeToTs(sqlType) {
  const normalized = sqlType.toLowerCase().replace(/\(.*\)/, '').trim();
  return TYPE_MAP[normalized] || 'unknown';
}

function pascalCase(str) {
  return str.replace(/(^|_)(\w)/g, (_, __, c) => c.toUpperCase());
}

function parseColumn(trimmed) {
  const colRe = /^\s*(\w+)\s+(\w+(?:\([^)]*\))?(?:\s*\[\])?)/;
  const colMatch = trimmed.match(colRe);
  if (!colMatch) return null;

  const colName = colMatch[1];
  const colType = colMatch[2];
  if (['PRIMARY', 'FOREIGN', 'UNIQUE', 'CHECK', 'CONSTRAINT', 'INDEX'].includes(colName.toUpperCase())) return null;

  const isArray = /\[\]/.test(colType);
  const baseType = colType.replace(/\[\]/, '').trim();
  const tsBase = sqlTypeToTs(baseType);
  const tsType = isArray ? `${tsBase}[]` : tsBase;

  const isNullable = !/NOT\s+NULL/i.test(trimmed) && !/PRIMARY\s+KEY/i.test(trimmed);
  const hasDefault = /DEFAULT/i.test(trimmed);

  return {
    name: colName,
    type: tsType,
    nullable: isNullable,
    optional: hasDefault || isNullable,
  };
}

function parseMigrations() {
  const files = fs.readdirSync(MIGRATIONS_DIR)
    .filter(f => f.endsWith('.sql'))
    .sort();

  const tablesByName = new Map();
  const tableRe = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(\w+)\s*\(([\s\S]*?)\);/gi;
  // ALTER TABLE foo ADD COLUMN [IF NOT EXISTS] bar <type> …;
  const alterRe = /ALTER\s+TABLE\s+(\w+)\s+ADD\s+COLUMN\s+(?:IF\s+NOT\s+EXISTS\s+)?([\s\S]*?);/gi;

  for (const file of files) {
    const sql = fs.readFileSync(path.join(MIGRATIONS_DIR, file), 'utf-8');

    // Pass 1: CREATE TABLE
    let match;
    while ((match = tableRe.exec(sql)) !== null) {
      const tableName = match[1];
      const body = match[2];
      const columns = [];

      for (const line of body.split('\n')) {
        const trimmed = line.trim();
        if (!trimmed || /^(--|PRIMARY|FOREIGN|UNIQUE|CHECK|CONSTRAINT|ALTER|ENABLE)/i.test(trimmed)) continue;
        const col = parseColumn(trimmed);
        if (col) columns.push(col);
      }

      if (columns.length) {
        const existing = tablesByName.get(tableName);
        if (existing) {
          // Merge: prefer latest CREATE TABLE shape but keep any previously
          // appended ALTER columns that aren't already defined.
          const names = new Set(columns.map(c => c.name));
          for (const c of existing.columns) if (!names.has(c.name)) columns.push(c);
        }
        tablesByName.set(tableName, {
          name: tableName,
          interfaceName: pascalCase(tableName),
          columns,
        });
      }
    }

    // Pass 2: ALTER TABLE ADD COLUMN — appends onto any table already seen
    let alter;
    while ((alter = alterRe.exec(sql)) !== null) {
      const tableName = alter[1];
      const body = alter[2].trim();
      const col = parseColumn(body);
      if (!col) continue;
      const existing = tablesByName.get(tableName);
      if (!existing) continue; // skip columns for tables we haven't modeled
      if (existing.columns.some(c => c.name === col.name)) continue;
      existing.columns.push(col);
    }
  }

  return Array.from(tablesByName.values());
}

function generateDts(tables) {
  const lines = [
    '// Auto-generated by scripts/gen-types.js — do not edit manually.',
    '// Generated from migrations/*.sql',
    '',
    'declare namespace DB {',
  ];

  for (const table of tables) {
    lines.push(`  /** Table: ${table.name} */`);
    lines.push(`  interface ${table.interfaceName} {`);
    for (const col of table.columns) {
      const opt = col.optional ? '?' : '';
      const nullSuffix = col.nullable ? ' | null' : '';
      lines.push(`    ${col.name}${opt}: ${col.type}${nullSuffix};`);
    }
    lines.push('  }');
    lines.push('');
  }

  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

// Main
const tables = parseMigrations();
const dts = generateDts(tables);
fs.writeFileSync(OUTPUT_FILE, dts, 'utf-8');
console.log(`Generated ${tables.length} interfaces → ${OUTPUT_FILE}`);
