#!/usr/bin/env node
/**
 * NICE — Generate TypeScript interfaces from SQL migration files.
 * Usage: node scripts/gen-types.js
 * Output: app/js/lib/db-types.d.ts
 *
 * Simple regex-based parser — not a full SQL parser.
 * Handles CREATE TABLE statements with common column types.
 */

const fs = require('fs');
const path = require('path');

const MIGRATIONS_DIR = path.resolve(__dirname, '..', 'migrations');
const OUTPUT_FILE = path.resolve(__dirname, '..', 'app', 'js', 'lib', 'db-types.d.ts');

// Map SQL types to TypeScript types
const TYPE_MAP = {
  'uuid': 'string',
  'text': 'string',
  'varchar': 'string',
  'char': 'string',
  'integer': 'number',
  'int': 'number',
  'bigint': 'number',
  'smallint': 'number',
  'serial': 'number',
  'float': 'number',
  'double': 'number',
  'numeric': 'number',
  'decimal': 'number',
  'real': 'number',
  'boolean': 'boolean',
  'bool': 'boolean',
  'jsonb': 'Record<string, unknown>',
  'json': 'Record<string, unknown>',
  'timestamptz': 'string',
  'timestamp': 'string',
  'date': 'string',
  'time': 'string',
};

function sqlTypeToTs(sqlType) {
  const normalized = sqlType.toLowerCase().replace(/\(.*\)/, '').trim();
  return TYPE_MAP[normalized] || 'unknown';
}

function pascalCase(str) {
  return str.replace(/(^|_)(\w)/g, (_, __, c) => c.toUpperCase());
}

function parseMigrations() {
  const files = fs.readdirSync(MIGRATIONS_DIR)
    .filter(f => f.endsWith('.sql'))
    .sort();

  const tables = [];
  const tableRe = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(\w+)\s*\(([\s\S]*?)\);/gi;
  const colRe = /^\s*(\w+)\s+(\w+(?:\([^)]*\))?)/;

  for (const file of files) {
    const sql = fs.readFileSync(path.join(MIGRATIONS_DIR, file), 'utf-8');
    let match;
    while ((match = tableRe.exec(sql)) !== null) {
      const tableName = match[1];
      const body = match[2];
      const columns = [];

      for (const line of body.split('\n')) {
        const trimmed = line.trim();
        // Skip constraints, comments, empty lines
        if (!trimmed || /^(--|PRIMARY|FOREIGN|UNIQUE|CHECK|CONSTRAINT|ALTER|ENABLE)/i.test(trimmed)) continue;

        const colMatch = trimmed.match(colRe);
        if (colMatch) {
          const colName = colMatch[1];
          const colType = colMatch[2];
          // Skip SQL keywords used as pseudo-columns
          if (['PRIMARY', 'FOREIGN', 'UNIQUE', 'CHECK', 'CONSTRAINT', 'INDEX'].includes(colName.toUpperCase())) continue;

          const isNullable = !/NOT\s+NULL/i.test(trimmed) && !/PRIMARY\s+KEY/i.test(trimmed);
          const hasDefault = /DEFAULT/i.test(trimmed);
          const tsType = sqlTypeToTs(colType);

          columns.push({
            name: colName,
            type: tsType,
            nullable: isNullable,
            optional: hasDefault || isNullable,
          });
        }
      }

      if (columns.length) {
        tables.push({ name: tableName, interfaceName: pascalCase(tableName), columns });
      }
    }
  }

  return tables;
}

function generateDts(tables) {
  const lines = [
    '// Auto-generated by scripts/gen-types.js — do not edit manually.',
    '// Generated from migrations/*.sql',
    '',
    'declare namespace DB {',
  ];

  for (const table of tables) {
    lines.push(`  /** Table: ${table.name} */`);
    lines.push(`  interface ${table.interfaceName} {`);
    for (const col of table.columns) {
      const opt = col.optional ? '?' : '';
      const nullSuffix = col.nullable ? ' | null' : '';
      lines.push(`    ${col.name}${opt}: ${col.type}${nullSuffix};`);
    }
    lines.push('  }');
    lines.push('');
  }

  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

// Main
const tables = parseMigrations();
const dts = generateDts(tables);
fs.writeFileSync(OUTPUT_FILE, dts, 'utf-8');
console.log(`Generated ${tables.length} interfaces → ${OUTPUT_FILE}`);
