-- Seed config.crew_roles for 229 catalog spaceships missing one.
-- Generated by scripts/seed-crew-roles.mjs on 2026-04-27T19:15:46.665Z.
--
-- The CrewMatcher (app/js/lib/crew-matcher.js, shipped #308) reads
-- config.crew_roles at ship activation. Tokens come from a bounded
-- vocabulary chosen so scoreMatch hits 90-100 against the catalog's
-- agent role/category values. Ships with crew_overrides (the 8
-- flagships from PR #309) are skipped — overrides take precedence.
--
-- jsonb_set with COALESCE preserves any other config keys that may be
-- present (none today, but defensively).

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","ops","design","support","operations"]$$::jsonb)
WHERE id = 'fleet-193' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["research","research","analytics","ops","content","operations"]$$::jsonb)
WHERE id = 'ship-128' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["finance","finance","analytics","ops","support","operations"]$$::jsonb)
WHERE id = 'fleet-100' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["marketing","marketing","content","design","analytics","sales"]$$::jsonb)
WHERE id = 'fleet-180' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["automation","engineering","analytics","security","ops","operations"]$$::jsonb)
WHERE id = 'fleet-37' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["legal","legal","research","analytics","ops","operations"]$$::jsonb)
WHERE id = 'fleet-29' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","content","design","engineering","ops","operations"]$$::jsonb)
WHERE id = 'fleet-178' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["design","engineering","ops","operations","sales","support"]$$::jsonb)
WHERE id = 'fleet-101' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","sales","marketing","operations","content"]$$::jsonb)
WHERE id = 'fleet-190' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","ops","support","sales","operations","analytics"]$$::jsonb)
WHERE id = 'fleet-140' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["automation","engineering","analytics","security","ops","operations"]$$::jsonb)
WHERE id = 'fleet-40' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","operations","analytics","engineering","automation","content","hr"]$$::jsonb)
WHERE id = 'ship-81' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","ops","marketing","support","operations","content"]$$::jsonb)
WHERE id = 'fleet-129' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","engineering","analytics","security","operations","sales","finance","support","content","research"]$$::jsonb)
WHERE id = 'ship-70' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["support","support","ops","operations","analytics","content"]$$::jsonb)
WHERE id = 'fleet-124' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","support","ops","engineering","marketing","operations"]$$::jsonb)
WHERE id = 'fleet-154' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["analytics","analytics","finance","ops","support","operations"]$$::jsonb)
WHERE id = 'fleet-112' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","content","ops","marketing","support","operations"]$$::jsonb)
WHERE id = 'fleet-155' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["automation","engineering","analytics","security","research","operations","ops","support","content","marketing","finance","legal","sales","hr","design","automation","engineering","analytics","security","research","operations","ops","support","content"]$$::jsonb)
WHERE id = 'ship-50' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","marketing","sales","content","operations"]$$::jsonb)
WHERE id = 'ship-120' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["marketing","marketing","content","design","analytics","operations"]$$::jsonb)
WHERE id = 'ship-99' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","content","content","marketing","design","analytics"]$$::jsonb)
WHERE id = 'ship-93' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","sales","analytics","legal","marketing","operations"]$$::jsonb)
WHERE id = 'fleet-114' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","sales","marketing","support","finance","operations"]$$::jsonb)
WHERE id = 'fleet-187' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["analytics","analytics","operations","legal","research","ops"]$$::jsonb)
WHERE id = 'fleet-30' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","sales","marketing","support","operations","content"]$$::jsonb)
WHERE id = 'ship-121' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","sales","marketing","support","operations","content"]$$::jsonb)
WHERE id = 'fleet-127' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","operations","sales","content","finance"]$$::jsonb)
WHERE id = 'fleet-199' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","operations","analytics","marketing","sales"]$$::jsonb)
WHERE id = 'fleet-122' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","engineering","marketing","legal","hr","sales","support","operations","finance","analytics","research","content","design","security","automation","ops","engineering","marketing","legal","hr","sales","support","operations","finance"]$$::jsonb)
WHERE id = 'fleet-48' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","ops","support","operations","sales","marketing"]$$::jsonb)
WHERE id = 'fleet-139' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["research","research","analytics","ops","operations","legal"]$$::jsonb)
WHERE id = 'ship-127' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["research","ops","operations","analytics","legal","support"]$$::jsonb)
WHERE id = 'fleet-38' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","sales","marketing","operations","content"]$$::jsonb)
WHERE id = 'fleet-164' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","ops","marketing","support","operations","content"]$$::jsonb)
WHERE id = 'fleet-128' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","legal","analytics","support","operations","finance"]$$::jsonb)
WHERE id = 'fleet-184' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["legal","legal","analytics","operations","ops","support"]$$::jsonb)
WHERE id = 'ship-109' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","engineering","analytics","support","finance"]$$::jsonb)
WHERE id = 'ship-131' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["research","ops","operations","analytics","content","finance"]$$::jsonb)
WHERE id = 'fleet-06' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["legal","legal","operations","analytics","ops","support"]$$::jsonb)
WHERE id = 'ship-108' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","ops","sales","support","analytics","operations"]$$::jsonb)
WHERE id = 'fleet-172' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","sales","marketing","support","operations","content"]$$::jsonb)
WHERE id = 'fleet-125' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","content","design","marketing","ops","operations"]$$::jsonb)
WHERE id = 'fleet-15' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","content","marketing","analytics","design","operations"]$$::jsonb)
WHERE id = 'fleet-20' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["finance","support","ops","sales","legal","operations"]$$::jsonb)
WHERE id = 'fleet-182' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["support","support","engineering","operations","content","analytics"]$$::jsonb)
WHERE id = 'ship-107' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","sales","marketing","operations","content"]$$::jsonb)
WHERE id = 'fleet-143' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","content","analytics","marketing","security"]$$::jsonb)
WHERE id = 'fleet-186' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["analytics","analytics","research","engineering","content","marketing"]$$::jsonb)
WHERE id = 'ship-88' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["support","support","analytics","operations","sales","content"]$$::jsonb)
WHERE id = 'ship-105' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["security","security","engineering","analytics","operations","ops"]$$::jsonb)
WHERE id = 'ship-134' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","analytics","ops","operations","research"]$$::jsonb)
WHERE id = 'ship-135' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["legal","legal","analytics","operations","security","ops"]$$::jsonb)
WHERE id = 'fleet-36' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","sales","legal","finance","analytics","operations"]$$::jsonb)
WHERE id = 'ship-103' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["security","security","engineering","ops","operations","legal","hr","analytics","sales","finance","marketing","content","design","research","automation","support","security","engineering","ops","operations","legal","hr","analytics","sales"]$$::jsonb)
WHERE id = 'ship-59' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","sales","operations","finance","analytics"]$$::jsonb)
WHERE id = 'fleet-115' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","sales","operations","finance","analytics"]$$::jsonb)
WHERE id = 'ship-111' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","research","analytics","ops","operations","security","support","content","sales"]$$::jsonb)
WHERE id = 'ship-77' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","research","analytics","automation","security","ops","operations","support","content","design","sales"]$$::jsonb)
WHERE id = 'ship-55' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","legal","ops","operations","support","analytics"]$$::jsonb)
WHERE id = 'fleet-156' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["hr","ops","operations","content","analytics","support"]$$::jsonb)
WHERE id = 'fleet-28' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","sales","marketing","operations","content"]$$::jsonb)
WHERE id = 'fleet-198' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","sales","operations","marketing","content"]$$::jsonb)
WHERE id = 'fleet-167' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","ops","operations","analytics","sales"]$$::jsonb)
WHERE id = 'fleet-194' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","marketing","support","ops","content","operations"]$$::jsonb)
WHERE id = 'fleet-02' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","ops","operations","engineering","support","analytics"]$$::jsonb)
WHERE id = 'ship-124' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","engineering","analytics","support","operations","design"]$$::jsonb)
WHERE id = 'fleet-21' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","engineering","analytics","support","automation","operations"]$$::jsonb)
WHERE id = 'ship-136' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","engineering","analytics","support","operations","design"]$$::jsonb)
WHERE id = 'fleet-13' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","ops","operations","sales","support"]$$::jsonb)
WHERE id = 'fleet-135' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["research","research","engineering","analytics","ops","operations","support","content","security","sales"]$$::jsonb)
WHERE id = 'ship-72' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["automation","engineering","analytics","security","ops","operations"]$$::jsonb)
WHERE id = 'fleet-43' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","sales","sales","marketing","analytics","operations"]$$::jsonb)
WHERE id = 'ship-101' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["marketing","sales","support","content","analytics","operations"]$$::jsonb)
WHERE id = 'fleet-18' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","analytics","marketing","operations","ops","support"]$$::jsonb)
WHERE id = 'fleet-25' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","operations","analytics","ops","support","sales"]$$::jsonb)
WHERE id = 'fleet-195' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","research","security","ops","operations","analytics","support","content","automation"]$$::jsonb)
WHERE id = 'ship-74' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["marketing","marketing","content","sales","ops","operations"]$$::jsonb)
WHERE id = 'ship-98' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","sales","marketing","support","content"]$$::jsonb)
WHERE id = 'fleet-110' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","sales","marketing","operations","content"]$$::jsonb)
WHERE id = 'ship-122' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["support","support","analytics","ops","operations","content"]$$::jsonb)
WHERE id = 'fleet-107' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["research","analytics","content","ops","operations","sales"]$$::jsonb)
WHERE id = 'ship-115' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["security","security","engineering","ops","operations","analytics","support","content","legal","hr","sales","finance"]$$::jsonb)
WHERE id = 'ship-46' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["research","ops","support","operations","analytics","legal"]$$::jsonb)
WHERE id = 'fleet-123' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","content","design","ops","operations","finance"]$$::jsonb)
WHERE id = 'ship-95' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["finance","finance","analytics","legal","ops","operations"]$$::jsonb)
WHERE id = 'ship-114' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["analytics","finance","sales","support","ops","operations"]$$::jsonb)
WHERE id = 'fleet-185' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","sales","marketing","operations","content"]$$::jsonb)
WHERE id = 'ship-123' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","engineering","legal","analytics","support"]$$::jsonb)
WHERE id = 'fleet-188' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","ops","operations","marketing","support","content"]$$::jsonb)
WHERE id = 'fleet-151' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","sales","marketing","operations","support","content"]$$::jsonb)
WHERE id = 'fleet-126' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["operations","sales","marketing","support","analytics","ops"]$$::jsonb)
WHERE id = 'ship-125' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["analytics","analytics","security","legal","ops","operations"]$$::jsonb)
WHERE id = 'fleet-35' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","sales","support","ops","operations","marketing"]$$::jsonb)
WHERE id = 'fleet-157' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","content","design","ops","operations"]$$::jsonb)
WHERE id = 'fleet-179' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["automation","ops","operations","analytics","sales","support"]$$::jsonb)
WHERE id = 'fleet-130' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","sales","marketing","operations","content"]$$::jsonb)
WHERE id = 'fleet-146' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","engineering","content","support","legal"]$$::jsonb)
WHERE id = 'fleet-34' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","operations","analytics","security","ops"]$$::jsonb)
WHERE id = 'fleet-42' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["marketing","marketing","analytics","content","engineering","design"]$$::jsonb)
WHERE id = 'ship-96' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","sales","operations","support","marketing","content"]$$::jsonb)
WHERE id = 'fleet-17' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","operations","sales","analytics","finance"]$$::jsonb)
WHERE id = 'ship-119' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","operations","analytics","finance","legal"]$$::jsonb)
WHERE id = 'fleet-08' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["research","research","analytics","engineering","ops","operations","content","support","design","automation","security","sales"]$$::jsonb)
WHERE id = 'ship-56' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","operations","analytics","hr","content"]$$::jsonb)
WHERE id = 'fleet-121' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","content","analytics","support","sales"]$$::jsonb)
WHERE id = 'fleet-161' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","engineering","operations","support","sales","analytics"]$$::jsonb)
WHERE id = 'fleet-133' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["marketing","marketing","sales","content","analytics","operations"]$$::jsonb)
WHERE id = 'fleet-196' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["marketing","sales","content","analytics","operations","support"]$$::jsonb)
WHERE id = 'ship-97' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","sales","support","operations","analytics","finance"]$$::jsonb)
WHERE id = 'ship-116' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["analytics","analytics","engineering","research","operations","ops"]$$::jsonb)
WHERE id = 'fleet-33' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["legal","legal","analytics","operations","content","ops"]$$::jsonb)
WHERE id = 'ship-110' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["design","content","sales","ops","operations","support"]$$::jsonb)
WHERE id = 'fleet-109' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","sales","marketing","support","operations","content"]$$::jsonb)
WHERE id = 'fleet-16' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","sales","support","ops","operations","marketing"]$$::jsonb)
WHERE id = 'fleet-150' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","ops","operations","sales","support","marketing"]$$::jsonb)
WHERE id = 'fleet-136' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","content","support","ops","operations","marketing"]$$::jsonb)
WHERE id = 'fleet-169' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["legal","legal","research","ops","operations","support"]$$::jsonb)
WHERE id = 'fleet-03' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["operations","sales","analytics","support","ops","content"]$$::jsonb)
WHERE id = 'ship-132' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["operations","ops","analytics","support","sales","content"]$$::jsonb)
WHERE id = 'fleet-14' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["marketing","analytics","engineering","content","operations","support"]$$::jsonb)
WHERE id = 'fleet-24' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","sales","support","marketing","analytics","operations"]$$::jsonb)
WHERE id = 'ship-126' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["research","analytics","content","ops","operations","sales"]$$::jsonb)
WHERE id = 'fleet-106' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["analytics","analytics","research","content","marketing","operations"]$$::jsonb)
WHERE id = 'ship-90' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["research","research","analytics","content","operations","sales"]$$::jsonb)
WHERE id = 'fleet-113' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["marketing","marketing","content","analytics","ops","operations"]$$::jsonb)
WHERE id = 'fleet-05' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","sales","marketing","operations","content"]$$::jsonb)
WHERE id = 'fleet-147' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","sales","marketing","support","content"]$$::jsonb)
WHERE id = 'fleet-132' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","sales","support","marketing","operations","content"]$$::jsonb)
WHERE id = 'fleet-120' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","content","content","marketing","analytics","design"]$$::jsonb)
WHERE id = 'fleet-09' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["support","content","analytics","ops","operations","engineering"]$$::jsonb)
WHERE id = 'fleet-22' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","content","marketing","analytics","ops","operations","sales","design","research","security","automation"]$$::jsonb)
WHERE id = 'ship-85' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","sales","finance","support","analytics","operations"]$$::jsonb)
WHERE id = 'fleet-162' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","support","ops","engineering","operations","marketing"]$$::jsonb)
WHERE id = 'fleet-191' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","sales","support","content","marketing"]$$::jsonb)
WHERE id = 'fleet-142' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","engineering","operations","analytics","support","security","content","research","sales","hr"]$$::jsonb)
WHERE id = 'ship-73' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","content","engineering","design","sales","operations"]$$::jsonb)
WHERE id = 'ship-94' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","content","engineering","ops","operations","sales"]$$::jsonb)
WHERE id = 'fleet-177' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","content","support","ops","operations","sales"]$$::jsonb)
WHERE id = 'fleet-168' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","content","analytics","sales","finance"]$$::jsonb)
WHERE id = 'ship-130' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","content","analytics","sales","finance"]$$::jsonb)
WHERE id = 'fleet-11' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","engineering","operations","support","security","analytics","content","research","sales","legal"]$$::jsonb)
WHERE id = 'ship-68' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","engineering","research","analytics","sales","content","marketing","ops","operations","design","automation"]$$::jsonb)
WHERE id = 'ship-86' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","support","ops","operations","marketing","content"]$$::jsonb)
WHERE id = 'fleet-159' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","sales","operations","analytics","finance"]$$::jsonb)
WHERE id = 'fleet-119' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","analytics","operations","security","ops"]$$::jsonb)
WHERE id = 'fleet-41' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","sales","marketing","operations","analytics","content"]$$::jsonb)
WHERE id = 'ship-102' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["legal","legal","research","analytics","operations","content"]$$::jsonb)
WHERE id = 'fleet-108' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["automation","engineering","operations","analytics","security","support"]$$::jsonb)
WHERE id = 'fleet-183' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","sales","marketing","operations","content"]$$::jsonb)
WHERE id = 'fleet-145' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","sales","support","marketing","content"]$$::jsonb)
WHERE id = 'fleet-137' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","support","ops","operations","marketing","content"]$$::jsonb)
WHERE id = 'fleet-152' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","operations","sales","analytics","finance"]$$::jsonb)
WHERE id = 'fleet-117' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","content","sales","ops","operations","marketing"]$$::jsonb)
WHERE id = 'fleet-173' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","operations","analytics","sales","finance"]$$::jsonb)
WHERE id = 'fleet-118' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","operations","analytics","sales","finance"]$$::jsonb)
WHERE id = 'ship-113' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","support","engineering","sales","analytics","content","security"]$$::jsonb)
WHERE id = 'ship-79' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","engineering","operations","support","sales","analytics"]$$::jsonb)
WHERE id = 'fleet-134' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","content","sales","marketing","ops","operations"]$$::jsonb)
WHERE id = 'fleet-175' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","content","engineering","sales","operations","design"]$$::jsonb)
WHERE id = 'ship-91' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["marketing","marketing","content","analytics","ops","operations"]$$::jsonb)
WHERE id = 'ship-100' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","engineering","support","sales","content"]$$::jsonb)
WHERE id = 'fleet-141' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["marketing","content","analytics","operations","ops","support"]$$::jsonb)
WHERE id = 'fleet-103' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["analytics","engineering","operations","ops","sales","research"]$$::jsonb)
WHERE id = 'fleet-26' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","sales","support","design","marketing"]$$::jsonb)
WHERE id = 'fleet-158' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["research","research","analytics","legal","operations","content"]$$::jsonb)
WHERE id = 'fleet-105' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["research","research","engineering","analytics","ops","operations","security","support","content","sales"]$$::jsonb)
WHERE id = 'ship-76' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","support","sales","finance","analytics"]$$::jsonb)
WHERE id = 'fleet-160' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","support","sales","finance","analytics"]$$::jsonb)
WHERE id = 'ship-129' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","analytics","operations","ops","content","finance"]$$::jsonb)
WHERE id = 'fleet-32' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["automation","ops","operations","analytics","sales","marketing"]$$::jsonb)
WHERE id = 'fleet-19' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","sales","marketing","support","operations","content"]$$::jsonb)
WHERE id = 'ship-104' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","sales","marketing","support","operations","content"]$$::jsonb)
WHERE id = 'fleet-07' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["analytics","analytics","operations","ops","content","support"]$$::jsonb)
WHERE id = 'fleet-45' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["hr","sales","analytics","ops","operations","content"]$$::jsonb)
WHERE id = 'ship-117' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["hr","sales","ops","operations","support","content"]$$::jsonb)
WHERE id = 'fleet-102' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","engineering","operations","support","analytics","content","research","automation"]$$::jsonb)
WHERE id = 'ship-78' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","sales","marketing","support","operations","content"]$$::jsonb)
WHERE id = 'fleet-04' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["analytics","analytics","sales","operations","content","research"]$$::jsonb)
WHERE id = 'ship-87' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","engineering","analytics","legal","support"]$$::jsonb)
WHERE id = 'fleet-44' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","ops","operations","security","analytics","support","content","research","sales"]$$::jsonb)
WHERE id = 'ship-67' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","sales","support","analytics","content"]$$::jsonb)
WHERE id = 'fleet-138' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","operations","analytics","ops","support"]$$::jsonb)
WHERE id = 'ship-133' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","marketing","sales","support","operations"]$$::jsonb)
WHERE id = 'fleet-01' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["security","engineering","ops","operations","analytics","support","content","research","sales","hr","legal","design"]$$::jsonb)
WHERE id = 'ship-64' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","sales","support","analytics","content"]$$::jsonb)
WHERE id = 'fleet-163' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","sales","support","analytics","content"]$$::jsonb)
WHERE id = 'fleet-165' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["research","research","engineering","analytics","design","content","operations","ops","support","sales","marketing","legal","security","automation","finance","hr","research","engineering","analytics","design","content","operations","ops","support"]$$::jsonb)
WHERE id = 'fleet-49' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","engineering","security","operations","analytics","support","content","sales","research","automation"]$$::jsonb)
WHERE id = 'ship-82' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","operations","analytics","automation","security"]$$::jsonb)
WHERE id = 'fleet-39' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","content","marketing","operations","analytics","support"]$$::jsonb)
WHERE id = 'fleet-23' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","operations","analytics","content","support"]$$::jsonb)
WHERE id = 'fleet-10' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","sales","operations","ops","analytics"]$$::jsonb)
WHERE id = 'fleet-192' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","engineering","security","operations","analytics","support","content","research","sales","hr","legal","design"]$$::jsonb)
WHERE id = 'ship-65' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","engineering","security","operations","support","content","analytics","sales","marketing","hr","research","automation"]$$::jsonb)
WHERE id = 'ship-53' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","engineering","research","operations","analytics","ops","content","sales","marketing","design","automation"]$$::jsonb)
WHERE id = 'ship-84' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","sales","support","content","marketing"]$$::jsonb)
WHERE id = 'fleet-149' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["analytics","analytics","research","support","operations","content"]$$::jsonb)
WHERE id = 'fleet-27' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["hr","ops","operations","sales","support","analytics"]$$::jsonb)
WHERE id = 'fleet-111' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["security","ops","operations","engineering","analytics","support","content","research","sales","hr"]$$::jsonb)
WHERE id = 'ship-69' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["analytics","analytics","operations","ops","engineering","support"]$$::jsonb)
WHERE id = 'ship-89' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","sales","marketing","operations","content"]$$::jsonb)
WHERE id = 'fleet-148' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["research","research","engineering","ops","operations","analytics","content","support","security","design","automation","sales"]$$::jsonb)
WHERE id = 'ship-57' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","content","sales","ops","operations","marketing"]$$::jsonb)
WHERE id = 'fleet-176' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["finance","analytics","ops","operations","support","legal"]$$::jsonb)
WHERE id = 'ship-118' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["analytics","finance","ops","operations","support","sales"]$$::jsonb)
WHERE id = 'fleet-181' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","content","content","engineering","design","support"]$$::jsonb)
WHERE id = 'ship-92' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["support","support","content","engineering","operations","analytics"]$$::jsonb)
WHERE id = 'ship-106' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","operations","engineering","analytics","content"]$$::jsonb)
WHERE id = 'fleet-31' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["analytics","content","ops","operations","support","sales"]$$::jsonb)
WHERE id = 'fleet-171' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","engineering","automation","security","analytics","ops","operations","research","content","design","support"]$$::jsonb)
WHERE id = 'ship-51' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","engineering","support","content","analytics","research","hr"]$$::jsonb)
WHERE id = 'ship-80' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","sales","ops","operations","support","content"]$$::jsonb)
WHERE id = 'fleet-153' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","ops","operations","support","analytics","research","content"]$$::jsonb)
WHERE id = 'ship-83' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","sales","support","analytics","content"]$$::jsonb)
WHERE id = 'fleet-189' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","content","support","ops","operations","sales"]$$::jsonb)
WHERE id = 'fleet-170' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","content","operations","ops","sales","support"]$$::jsonb)
WHERE id = 'fleet-104' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["support","support","content","ops","operations","analytics"]$$::jsonb)
WHERE id = 'fleet-166' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["security","security","engineering","ops","operations","analytics","content","research","hr","support","legal","automation"]$$::jsonb)
WHERE id = 'ship-58' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["security","engineering","ops","operations","analytics","support","content","research","sales","hr","legal","design"]$$::jsonb)
WHERE id = 'ship-62' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["engineering","engineering","research","analytics","ops","operations","security","support","content","hr","design","automation"]$$::jsonb)
WHERE id = 'ship-61' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","sales","operations","analytics","finance"]$$::jsonb)
WHERE id = 'ship-112' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","operations","sales","analytics","finance"]$$::jsonb)
WHERE id = 'fleet-116' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["content","content","design","ops","operations","sales"]$$::jsonb)
WHERE id = 'fleet-174' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["analytics","finance","research","legal","ops","operations"]$$::jsonb)
WHERE id = 'fleet-12' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","operations","sales","support","content","marketing"]$$::jsonb)
WHERE id = 'fleet-197' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["security","ops","engineering","operations","analytics","support","content","research","hr","legal"]$$::jsonb)
WHERE id = 'ship-75' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["sales","ops","support","marketing","operations","content"]$$::jsonb)
WHERE id = 'fleet-131' AND type = 'spaceship' AND scope = 'catalog';

UPDATE blueprints
SET config = jsonb_set(COALESCE(config, '{}'::jsonb), '{crew_roles}', $$["ops","support","sales","marketing","operations","content"]$$::jsonb)
WHERE id = 'fleet-144' AND type = 'spaceship' AND scope = 'catalog';
