// Auto-generated by scripts/gen-types.js — do not edit manually.
// Generated from migrations/*.sql

declare namespace DB {
  /** Table: profiles */
  interface Profiles {
    id: string;
    display_name?: string | null;
    avatar_url?: string | null;
    plan?: string | null;
    fuel_balance?: number | null;
    xp?: number | null;
    achievements?: Record<string, unknown> | null;
    created_at?: string | null;
    updated_at?: string | null;
    stripe_customer_id?: string | null;
  }

  /** Table: user_agents */
  interface UserAgents {
    id?: string;
    user_id?: string | null;
    name: string;
    blueprint_id?: string | null;
    config?: Record<string, unknown> | null;
    status?: string | null;
    created_at?: string | null;
    updated_at?: string | null;
  }

  /** Table: user_spaceships */
  interface UserSpaceships {
    id?: string;
    user_id?: string | null;
    name: string;
    blueprint_id?: string | null;
    slots?: Record<string, unknown> | null;
    status?: string | null;
    created_at?: string | null;
    updated_at?: string | null;
  }

  /** Table: tasks */
  interface Tasks {
    id?: string;
    user_id?: string | null;
    title: string;
    agent_id?: string | null;
    agent_name?: string | null;
    status?: string | null;
    priority?: string | null;
    progress?: number | null;
    result?: string | null;
    created_at?: string | null;
    completed_at?: string | null;
  }

  /** Table: ship_log */
  interface ShipLog {
    id?: string;
    spaceship_id?: string | null;
    agent_id?: string | null;
    role?: string | null;
    content: string;
    metadata?: Record<string, unknown> | null;
    created_at?: string | null;
  }

  /** Table: vault_secrets */
  interface VaultSecrets {
    id?: string;
    user_id?: string | null;
    name: string;
    service?: string | null;
    encrypted_value?: string | null;
    status?: string | null;
    created_at?: string | null;
    last_used?: string | null;
  }

  /** Table: fuel_usage */
  interface FuelUsage {
    id?: string;
    user_id?: string | null;
    model?: string | null;
    input_tokens?: number | null;
    output_tokens?: number | null;
    fuel_cost?: number | null;
    agent_id?: string | null;
    spaceship_id?: string | null;
    created_at?: string | null;
  }

  /** Table: fuel_purchases */
  interface FuelPurchases {
    id?: string;
    user_id?: string | null;
    amount?: number;
    fuel_amount?: number;
    payment_method?: string | null;
    stripe_session_id?: string | null;
    created_at?: string | null;
  }

  /** Table: audit_log */
  interface AuditLog {
    id?: string;
    user_id?: string | null;
    type: string;
    description?: string | null;
    metadata?: Record<string, unknown> | null;
    created_at?: string | null;
  }

  /** Table: error_log */
  interface ErrorLog {
    id?: string;
    user_id?: string | null;
    message?: string | null;
    source?: string | null;
    line?: number | null;
    col?: number | null;
    stack?: string | null;
    url?: string | null;
    user_agent?: string | null;
    created_at?: string | null;
  }

  /** Table: notifications */
  interface Notifications {
    id?: string;
    user_id?: string | null;
    type?: string | null;
    title?: string | null;
    message?: string | null;
    read?: boolean | null;
    created_at?: string | null;
  }

  /** Table: workflows */
  interface Workflows {
    id?: string;
    user_id?: string | null;
    name: string;
    description?: string | null;
    steps?: Record<string, unknown> | null;
    status?: string | null;
    created_at?: string | null;
    updated_at?: string | null;
  }

  /** Table: user_workflows */
  interface UserWorkflows {
    id: string;
    user_id?: string | null;
    name?: string;
    nodes?: string | null;
    connections?: string | null;
    trigger?: string | null;
    created_at?: string | null;
    updated_at?: string | null;
  }

  /** Table: referrals */
  interface Referrals {
    id?: string;
    referrer_id?: string | null;
    referred_id?: string | null;
    status?: string | null;
    bonus_fuel_sent?: number | null;
    created_at?: string | null;
    updated_at?: string | null;
  }

  /** Table: integrations */
  interface Integrations {
    id?: string;
    user_id?: string | null;
    service: string;
    status?: string | null;
    config?: Record<string, unknown> | null;
    created_at?: string | null;
    updated_at?: string | null;
  }

  /** Table: station_invites */
  interface StationInvites {
    id?: string;
    station_id: string;
    invited_email: string;
    invited_by?: string | null;
    status?: string | null;
    created_at?: string | null;
    updated_at?: string | null;
  }

  /** Table: user_shared_agents */
  interface UserSharedAgents {
    id?: string;
    agent_id: string;
    shared_by?: string | null;
    shared_with_email: string;
    permissions?: string | null;
    created_at?: string | null;
  }

  /** Table: workflow_runs */
  interface WorkflowRuns {
    id?: string;
    user_id?: string | null;
    workflow_id: string;
    status?: string | null;
    started_at?: string | null;
    completed_at?: string | null;
    result?: Record<string, unknown> | null;
    created_at?: string | null;
  }

  /** Table: subscriptions */
  interface Subscriptions {
    id?: string;
    user_id: string;
    stripe_customer_id?: string | null;
    stripe_subscription_id?: string | null;
    plan?: string;
    status?: string;
    current_period_start?: string | null;
    current_period_end?: string | null;
    cancel_at_period_end?: boolean | null;
    created_at?: string | null;
    updated_at?: string | null;
    addons?: string[];
  }

  /** Table: fuel_transactions */
  interface FuelTransactions {
    id?: string;
    user_id: string;
    type: string;
    amount: number;
    balance_after: number;
    description?: string | null;
    reference_id?: string | null;
    created_at?: string | null;
  }

  /** Table: blueprints */
  interface Blueprints {
    id: string;
    serial_key: string;
    type: string;
    name: string;
    description?: string | null;
    flavor?: string | null;
    category?: string | null;
    rarity?: string | null;
    tags?: string[] | null;
    config?: Record<string, unknown> | null;
    stats?: Record<string, unknown> | null;
    metadata?: Record<string, unknown> | null;
    is_public?: boolean | null;
    creator_id?: string | null;
    rating_avg?: number | null;
    activation_count?: number | null;
    search_vector?: unknown | null;
    created_at?: string | null;
    updated_at?: string | null;
  }

  /** Table: mcp_connections */
  interface McpConnections {
    id?: string;
    user_id: string;
    spaceship_id: string;
    name: string;
    server_url?: string | null;
    transport?: string;
    auth_type?: string;
    auth_config?: Record<string, unknown> | null;
    available_tools?: Record<string, unknown> | null;
    status?: string;
    created_at?: string | null;
    updated_at?: string | null;
  }

  /** Table: api_connections */
  interface ApiConnections {
    id?: string;
    user_id: string;
    service: string;
    api_key_ref?: string | null;
    spaceship_ids?: string[] | null;
    status?: string;
    config?: Record<string, unknown> | null;
    created_at?: string | null;
    updated_at?: string | null;
  }

  /** Table: token_balances */
  interface TokenBalances {
    user_id: string;
    balance?: number;
    free_tier_remaining?: number;
    lifetime_purchased?: number;
    lifetime_used?: number;
    updated_at?: string;
    pools?: Record<string, unknown>;
    period_end?: string | null;
  }

  /** Table: token_transactions */
  interface TokenTransactions {
    id?: string;
    user_id: string;
    type: string;
    pool?: string;
    amount: number;
    balance_after: number;
    description?: string | null;
    reference_id?: string | null;
    created_at?: string;
  }

}
