// Auto-generated by scripts/gen-types.js — do not edit manually.
// Generated from migrations/*.sql

declare namespace DB {
  /** Table: profiles */
  interface Profiles {
    id: string;
    display_name?: string | null;
    avatar_url?: string | null;
    plan?: string | null;
    fuel_balance?: number | null;
    xp?: number | null;
    achievements?: Record<string, unknown> | null;
    created_at?: string | null;
    updated_at?: string | null;
  }

  /** Table: user_agents */
  interface UserAgents {
    id?: string;
    user_id?: string | null;
    name: string;
    blueprint_id?: string | null;
    config?: Record<string, unknown> | null;
    status?: string | null;
    created_at?: string | null;
    updated_at?: string | null;
  }

  /** Table: user_spaceships */
  interface UserSpaceships {
    id?: string;
    user_id?: string | null;
    name: string;
    blueprint_id?: string | null;
    slots?: Record<string, unknown> | null;
    status?: string | null;
    created_at?: string | null;
    updated_at?: string | null;
  }

  /** Table: tasks */
  interface Tasks {
    id?: string;
    user_id?: string | null;
    title: string;
    agent_id?: string | null;
    agent_name?: string | null;
    status?: string | null;
    priority?: string | null;
    progress?: number | null;
    result?: string | null;
    created_at?: string | null;
    completed_at?: string | null;
  }

  /** Table: ship_log */
  interface ShipLog {
    id?: string;
    spaceship_id?: string | null;
    agent_id?: string | null;
    role?: string | null;
    content: string;
    metadata?: Record<string, unknown> | null;
    created_at?: string | null;
  }

  /** Table: vault_secrets */
  interface VaultSecrets {
    id?: string;
    user_id?: string | null;
    name: string;
    service?: string | null;
    encrypted_value?: string | null;
    status?: string | null;
    created_at?: string | null;
    last_used?: string | null;
  }

  /** Table: fuel_usage */
  interface FuelUsage {
    id?: string;
    user_id?: string | null;
    model?: string | null;
    input_tokens?: number | null;
    output_tokens?: number | null;
    fuel_cost?: number | null;
    agent_id?: string | null;
    spaceship_id?: string | null;
    created_at?: string | null;
  }

  /** Table: audit_log */
  interface AuditLog {
    id?: string;
    user_id?: string | null;
    type: string;
    description?: string | null;
    metadata?: Record<string, unknown> | null;
    created_at?: string | null;
  }

  /** Table: error_log */
  interface ErrorLog {
    id?: string;
    user_id?: string | null;
    message?: string | null;
    source?: string | null;
    line?: number | null;
    col?: number | null;
    stack?: string | null;
    url?: string | null;
    user_agent?: string | null;
    created_at?: string | null;
  }

  /** Table: notifications */
  interface Notifications {
    id?: string;
    user_id?: string | null;
    type?: string | null;
    title?: string | null;
    message?: string | null;
    read?: boolean | null;
    created_at?: string | null;
  }

  /** Table: workflows */
  interface Workflows {
    id?: string;
    user_id?: string | null;
    name: string;
    description?: string | null;
    steps?: Record<string, unknown> | null;
    status?: string | null;
    created_at?: string | null;
    updated_at?: string | null;
  }
}
