/* ═══════════════════════════════════════════════════════════════════
   NICE — Media Tools
   Registers image/video generation tools in ToolRegistry.
   Agents can call these tools during missions to create visual content.
═══════════════════════════════════════════════════════════════════ */

const MediaTools = (() => {

  function init() {
    if (typeof ToolRegistry === 'undefined') return;

    /* ── Generate Image ── */
    ToolRegistry.register({
      id: 'generate-image',
      name: 'Generate Image',
      description: 'Generate an image from a text description using AI. Returns an image URL. Use for social media posts, marketing materials, product photos, etc.',
      schema: {
        type: 'object',
        properties: {
          prompt: { type: 'string', description: 'Detailed description of the image to generate. Be specific about style, composition, colors, mood.' },
          size: { type: 'string', enum: ['1024x1024', '1792x1024', '1024x1792'], description: 'Image dimensions. Square (1024x1024) for Instagram, landscape (1792x1024) for Twitter/Facebook, portrait (1024x1792) for stories.' },
          style: { type: 'string', enum: ['vivid', 'natural'], description: 'vivid = dramatic/artistic, natural = photorealistic' },
          quality: { type: 'string', enum: ['standard', 'hd'], description: 'standard = fast/cheap, hd = higher detail' },
        },
        required: ['prompt'],
      },
      execute: async (input) => {
        try {
          const result = await _callMediaAPI({
            prompt: input.prompt,
            size: input.size || '1024x1024',
            style: input.style || 'vivid',
            quality: input.quality || 'standard',
          });

          if (result.error) return `Error generating image: ${result.error}`;

          // Store the URL in a way the mission result renderer can find it
          _storeGeneratedImage(result);

          return `Image generated successfully!\n\n![Generated Image](${result.stored_url || result.url})\n\nPrompt used: ${result.revised_prompt || input.prompt}\nProvider: ${result.provider} (${result.model})\nSize: ${result.size}`;
        } catch (err) {
          return `Error: ${err.message || 'Image generation failed'}`;
        }
      },
    });

    /* ── Generate Social Post (image + caption) ── */
    ToolRegistry.register({
      id: 'generate-social-post',
      name: 'Generate Social Post',
      description: 'Generate a complete social media post with an AI-generated image and caption. Returns image URL + formatted post text.',
      schema: {
        type: 'object',
        properties: {
          topic: { type: 'string', description: 'What the post is about' },
          platform: { type: 'string', enum: ['instagram', 'twitter', 'facebook', 'linkedin'], description: 'Target platform (affects image size and caption style)' },
          tone: { type: 'string', enum: ['professional', 'casual', 'fun', 'inspiring', 'informative'], description: 'Tone of the caption' },
          image_prompt: { type: 'string', description: 'Specific description for the image. If not provided, will be auto-generated from the topic.' },
        },
        required: ['topic'],
      },
      execute: async (input) => {
        try {
          const platform = input.platform || 'instagram';
          const sizeMap = {
            instagram: '1024x1024',
            twitter: '1792x1024',
            facebook: '1792x1024',
            linkedin: '1792x1024',
          };

          // Generate image
          const imagePrompt = input.image_prompt || `Professional ${input.tone || 'vivid'} photo for a ${platform} post about: ${input.topic}. High quality, engaging, social media optimized.`;
          const result = await _callMediaAPI({
            prompt: imagePrompt,
            size: sizeMap[platform] || '1024x1024',
            style: 'vivid',
            quality: 'standard',
          });

          if (result.error) return `Error generating image: ${result.error}`;

          _storeGeneratedImage(result);

          const imageUrl = result.stored_url || result.url;
          return `## Social Post Ready\n\n![Post Image](${imageUrl})\n\n**Platform:** ${platform}\n**Topic:** ${input.topic}\n**Tone:** ${input.tone || 'casual'}\n\n---\n\n*Image generated by ${result.provider} (${result.model}). Edit the caption in the mission result and copy to your ${platform} app.*`;
        } catch (err) {
          return `Error: ${err.message || 'Social post generation failed'}`;
        }
      },
    });

    console.log('[MediaTools] Registered generate-image and generate-social-post tools');
  }

  /* ── API Call ── */
  async function _callMediaAPI(opts) {
    if (typeof SB === 'undefined' || !SB.isReady()) {
      throw new Error('Supabase not connected');
    }

    const { data, error } = await SB.functions.invoke('nice-media', {
      body: {
        prompt: opts.prompt,
        size: opts.size,
        quality: opts.quality,
        style: opts.style,
        provider: opts.provider,
        aspect_ratio: opts.aspect_ratio,
        store: true,
      },
    });

    if (error) throw new Error(typeof error === 'string' ? error : 'Media API error');
    return data;
  }

  /* ── Store reference for result rendering ── */
  function _storeGeneratedImage(result) {
    try {
      const images = JSON.parse(sessionStorage.getItem('nice-generated-images') || '[]');
      images.push({
        url: result.stored_url || result.url,
        prompt: result.revised_prompt || '',
        provider: result.provider,
        model: result.model,
        timestamp: Date.now(),
      });
      sessionStorage.setItem('nice-generated-images', JSON.stringify(images));
    } catch {}
  }

  /* ── Public: generate directly (for UI buttons) ── */
  async function generate(prompt, opts = {}) {
    return _callMediaAPI({ prompt, ...opts });
  }

  return { init, generate };
})();

// Auto-init when ToolRegistry is ready
if (typeof document !== 'undefined') {
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', () => setTimeout(() => MediaTools.init(), 300));
  } else {
    setTimeout(() => MediaTools.init(), 300);
  }
}
